#!/usr/bin/env sh

if test -z "$EAVE_HOME"
then
    echo "EAVE_HOME is not set. Set EAVE_HOME to the directory containing this repository and try again."
    exit 1
fi

sudo ln -s \
    "$EAVE_HOME/eave-dev-certs/eave.dev/cert.pem" \
    "/usr/local/share/ca-certificates/eave.dev.crt"


# FIXME: This only works on Debian.
sudo dpkg-reconfigure ca-certificates

# TODO: Check to see if these are already present
sudo -- sh -ec "echo \"\n\n127.0.0.1 www.eave.dev api.eave.dev slack.eave.dev\" >> /etc/hosts"

# TODO: Does this work on macOS?
sudo certutil -d "sql:$HOME/.pki/nssdb" -A -t "C,," -n "eave.dev self-signed" -i "$EAVE_HOME/eave-dev-certs/eave.dev/cert.pem"
