from enum import StrEnum


class EVConnectorType(StrEnum):
    """https://developers.google.com/maps/documentation/places/web-service/reference/rest/v1/places#EVConnectorType"""

    EV_CONNECTOR_TYPE_UNSPECIFIED = "EV_CONNECTOR_TYPE_UNSPECIFIED"
    EV_CONNECTOR_TYPE_OTHER = "EV_CONNECTOR_TYPE_OTHER"
    EV_CONNECTOR_TYPE_J1772 = "EV_CONNECTOR_TYPE_J1772"
    EV_CONNECTOR_TYPE_TYPE_2 = "EV_CONNECTOR_TYPE_TYPE_2"
    EV_CONNECTOR_TYPE_CHADEMO = "EV_CONNECTOR_TYPE_CHADEMO"
    EV_CONNECTOR_TYPE_CCS_COMBO_1 = "EV_CONNECTOR_TYPE_CCS_COMBO_1"
    EV_CONNECTOR_TYPE_CCS_COMBO_2 = "EV_CONNECTOR_TYPE_CCS_COMBO_2"
    EV_CONNECTOR_TYPE_TESLA = "EV_CONNECTOR_TYPE_TESLA"
    EV_CONNECTOR_TYPE_UNSPECIFIED_GB_T = "EV_CONNECTOR_TYPE_UNSPECIFIED_GB_T"
    EV_CONNECTOR_TYPE_UNSPECIFIED_WALL_OUTLET = "EV_CONNECTOR_TYPE_UNSPECIFIED_WALL_OUTLET"
