---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "${SHARED_CONFIGMAP_NAME}"
  namespace: "${NAMESPACE}"
data:
  GOOGLE_CLOUD_PROJECT: "${GOOGLE_CLOUD_PROJECT}"
  EAVE_METABASE_BASE_PUBLIC: "${EAVE_METABASE_BASE_PUBLIC}"
  EAVE_METABASE_BASE_INTERNAL: "${EAVE_METABASE_BASE_INTERNAL}"
  EAVE_API_BASE_PUBLIC: "${EAVE_API_BASE_PUBLIC}"
  EAVE_API_BASE_INTERNAL: "${EAVE_API_BASE_INTERNAL}"
  EAVE_DASHBOARD_BASE_PUBLIC: "${EAVE_DASHBOARD_BASE_PUBLIC}"
  EAVE_DASHBOARD_BASE_INTERNAL: "${EAVE_DASHBOARD_BASE_INTERNAL}"
  EAVE_GITHUB_APP_BASE_PUBLIC: "${EAVE_GITHUB_APP_BASE_PUBLIC}"
  EAVE_GITHUB_APP_BASE_INTERNAL: "${EAVE_GITHUB_APP_BASE_INTERNAL}"
  EAVE_ROOT_DOMAIN: "${EAVE_ROOT_DOMAIN}"
  EAVE_COOKIE_DOMAIN: "${EAVE_COOKIE_DOMAIN}"