---
# Noop service; always fails.
# This can be used for default backend in an Ingress when you want to block certain routes from being accessed externally.
apiVersion: v1
kind: Service
metadata:
  name: noop
  namespace: "${NAMESPACE}"
spec:
  type: ExternalName
  externalName: eave.fyi


---
# Standard app healthcheck/backend config
# Assumes the app is listening on port 8000 and has a /status endpoint.
# Also:
# - Removes any "server" response header, for security.
# - Adds a special header to indicate to the backend that the request flowed through this ingress.
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: shared-bc
spec:
  healthCheck:
    type: HTTP
    requestPath: /status
    port: 8000
  logging:
    enable: true
    sampleRate: 0.5
  customRequestHeaders:
    headers:
    - "eave-lb: 1"
  customResponseHeaders:
    headers:
      - "server: n/a"

---
# Standard app frontend config.
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: shared-fc
  namespace: "${NAMESPACE}"
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
