---
# Noop service; always fails.
# This can be used for default backend in an Ingress when you want to block certain routes from being accessed externally.
apiVersion: v1
kind: Service
metadata:
  name: noop
  namespace: "${NAMESPACE}"
spec:
  type: ExternalName
  externalName: eave.fyi


---
# Standard app healthcheck/backend config
# Assumes the app is listening on port 8000 and has a /status endpoint.
# Also removes any "server" response header, for security.
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: shared-bc
spec:
  healthCheck:
    type: HTTP
    requestPath: /status
    port: 8000
  customResponseHeaders:
    headers:
      - "server: unspecified"

---
# Standard app frontend config.
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: shared-fc
  namespace: "${NAMESPACE}"
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
