import eave.stdlib.util
from .base import BaseTestCase


def confluence_document_response(test_case: BaseTestCase) -> eave.stdlib.util.JsonObject:
    return {
        "id": test_case.anystring("confluence_document_response.id"),
        "type": "page",
        "status": "current",
        "title": test_case.anystring("confluence_document_response.title"),
        "space": {
            "id": 229380,
            "key": "EAVE",
            "name": "Eave",
            "type": "global",
            "status": "current",
            "_expandable": {
                "settings": "/rest/api/space/EAVE/settings",
                "metadata": "",
                "operations": "",
                "lookAndFeel": "/rest/api/settings/lookandfeel?spaceKey=EAVE",
                "identifiers": "",
                "permissions": "",
                "icon": "",
                "description": "",
                "theme": "/rest/api/space/EAVE/theme",
                "history": "",
                "homepage": "/rest/api/content/229464",
            },
            "_links": {"webui": "/spaces/EAVE", "self": "https://eave-fyi.atlassian.net/wiki/rest/api/space/EAVE"},
        },
        "history": {
            "latest": True,
            "createdBy": {
                "type": "known",
                "accountId": "63a5faccb790087ed70fc684",
                "accountType": "atlassian",
                "email": "bryan@eave.fyi",
                "publicName": "Bryan Ricker",
                "profilePicture": {
                    "path": "/wiki/aa-avatar/63a5faccb790087ed70fc684",
                    "width": 48,
                    "height": 48,
                    "isDefault": False,
                },
                "displayName": "Bryan Ricker",
                "isExternalCollaborator": False,
                "_expandable": {"operations": "", "personalSpace": ""},
                "_links": {
                    "self": "https://eave-fyi.atlassian.net/wiki/rest/api/user?accountId=63a5faccb790087ed70fc684"
                },
            },
            "createdDate": "2023-01-08T23:36:45.274Z",
            "_expandable": {
                "lastUpdated": "",
                "previousVersion": "",
                "contributors": "",
                "nextVersion": "",
                "ownedBy": "",
            },
            "_links": {"self": "https://eave-fyi.atlassian.net/wiki/rest/api/content/3375127/history"},
        },
        "version": {
            "by": {
                "type": "known",
                "accountId": "63a5faccb790087ed70fc684",
                "accountType": "atlassian",
                "email": "bryan@eave.fyi",
                "publicName": "Bryan Ricker",
                "profilePicture": {
                    "path": "/wiki/aa-avatar/63a5faccb790087ed70fc684",
                    "width": 48,
                    "height": 48,
                    "isDefault": False,
                },
                "displayName": "Bryan Ricker",
                "isExternalCollaborator": False,
                "_expandable": {"operations": "", "personalSpace": ""},
                "_links": {
                    "self": "https://eave-fyi.atlassian.net/wiki/rest/api/user?accountId=63a5faccb790087ed70fc684"
                },
            },
            "when": "2023-01-08T23:36:45.274Z",
            "friendlyWhen": "just a moment ago",
            "message": "",
            "number": 1,
            "minorEdit": False,
            "confRev": "confluence$content$3375127.2",
            "contentTypeModified": False,
            "_expandable": {"collaborators": "", "content": "/rest/api/content/3375127"},
            "_links": {"self": "https://eave-fyi.atlassian.net/wiki/rest/api/content/3375127/version/1"},
        },
        "ancestors": [
            {
                "id": "229464",
                "type": "page",
                "status": "current",
                "title": "Eave",
                "macroRenderedOutput": {},
                "extensions": {"position": 655},
                "_expandable": {
                    "container": "/rest/api/space/EAVE",
                    "metadata": "",
                    "restrictions": "/rest/api/content/229464/restriction/byOperation",
                    "history": "/rest/api/content/229464/history",
                    "body": "",
                    "version": "",
                    "descendants": "/rest/api/content/229464/descendant",
                    "space": "/rest/api/space/EAVE",
                    "childTypes": "",
                    "schedulePublishInfo": "",
                    "operations": "",
                    "schedulePublishDate": "",
                    "children": "/rest/api/content/229464/child",
                    "ancestors": "",
                },
                "_links": {
                    "self": "https://eave-fyi.atlassian.net/wiki/rest/api/content/229464",
                    "tinyui": "/x/WIAD",
                    "editui": "/pages/resumedraft.action?draftId=229464",
                    "webui": "/spaces/EAVE/overview",
                },
            }
        ],
        "container": {
            "id": 229380,
            "key": "EAVE",
            "name": "Eave",
            "type": "global",
            "status": "current",
            "history": {
                "createdBy": {
                    "type": "known",
                    "accountId": "63a5faccb790087ed70fc684",
                    "accountType": "atlassian",
                    "email": "bryan@eave.fyi",
                    "publicName": "Bryan Ricker",
                    "profilePicture": {
                        "path": "/wiki/aa-avatar/63a5faccb790087ed70fc684",
                        "width": 48,
                        "height": 48,
                        "isDefault": False,
                    },
                    "displayName": "Bryan Ricker",
                    "isExternalCollaborator": False,
                    "_expandable": {"operations": "", "personalSpace": ""},
                    "_links": {
                        "self": "https://eave-fyi.atlassian.net/wiki/rest/api/user?accountId=63a5faccb790087ed70fc684"
                    },
                },
                "createdDate": "2022-12-23T19:06:29.653Z",
            },
            "_expandable": {
                "settings": "/rest/api/space/EAVE/settings",
                "metadata": "",
                "operations": "",
                "lookAndFeel": "/rest/api/settings/lookandfeel?spaceKey=EAVE",
                "identifiers": "",
                "permissions": "",
                "icon": "",
                "description": "",
                "theme": "/rest/api/space/EAVE/theme",
                "homepage": "/rest/api/content/229464",
            },
            "_links": {"webui": "/spaces/EAVE", "self": "https://eave-fyi.atlassian.net/wiki/rest/api/space/EAVE"},
        },
        "macroRenderedOutput": {},
        "body": {
            "storage": {
                "value": "<h1>Test Body</h1>\\n\\n<p>Hello</p>\\n\\n<h3>Smaller Header</h3>\\n\\n<p>OK</p>",
                "representation": "storage",
                "embeddedContent": [],
                "_expandable": {"content": "/rest/api/content/3375127"},
            },
            "_expandable": {
                "editor": "",
                "atlas_doc_format": "",
                "view": "",
                "export_view": "",
                "styled_view": "",
                "dynamic": "",
                "editor2": "",
                "anonymous_export_view": "",
            },
        },
        "extensions": {"position": 939968483},
        "_expandable": {
            "childTypes": "",
            "schedulePublishInfo": "",
            "metadata": "",
            "operations": "",
            "schedulePublishDate": "",
            "children": "/rest/api/content/3375127/child",
            "restrictions": "/rest/api/content/3375127/restriction/byOperation",
            "descendants": "/rest/api/content/3375127/descendant",
        },
        "_links": {
            "editui": "/pages/resumedraft.action?draftId=3375127",
            "webui": "/spaces/EAVE/pages/3375127/Test+Title+917c1747-5d52-421e-aaf6-05ad519d5dd8",
            "context": "/wiki",
            "self": "https://eave-fyi.atlassian.net/wiki/rest/api/content/3375127",
            "tinyui": "/" + test_case.anystring("confluence_document_response._links.tinyui"),
            "collection": "/rest/api/content",
            "base": test_case.anystring("confluence_document_response._links.base"),
        },
    }
