#!/usr/bin/env bash

set -eu

source "${EAVE_HOME}"/develop/functions.bash

(
	node-lint .
	if test -z "${_ONLY_THIS_MODULE:-}"; then
		"${EAVE_HOME}"/libs/eave-stdlib-ts/bin/lint
		"${EAVE_HOME}"/libs/eave-pubsub-schemas/typescript/bin/lint
	fi
)
