#!/usr/bin/env bash

set -eu

source "${EAVE_HOME}"/develop/functions.bash

(
	node-test .
	if test -z "${_ONLY_THIS_MODULE:-}"; then
		"${EAVE_HOME}"/libs/eave-stdlib-ts/bin/test
		"${EAVE_HOME}"/libs/eave-pubsub-schemas/typescript/bin/test
	fi
)
