services:
  postgres:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    ports:
      - "5431:5432"
    volumes:
      - .pgdata:/var/lib/postgresql/data
    env_file:
      - path: .env
        required: false
    environment:
      # This is the password for the default postgres user, required by the Postgres Docker container. This has nothing to do with the metabase application users.
      - POSTGRES_PASSWORD=unsafe

  metabase:
    image: metabase/metabase-enterprise:latest
    ports:
      - "5400:3000"
    depends_on:
      - postgres
    env_file:
      - path: .env
        required: false
      - path: ./develop/shared/metabase.share.env
    environment:
      - MB_DB_HOST=postgres
      - MB_DB_PORT=5432
      - MB_DB_DBNAME=metabase_db_dev
      - MB_DB_USER=metabase_app_dev
      - MB_DB_PASS=unsafe

  core:
    build:
      context: .
      dockerfile: ./docker/core/Dockerfile
    volumes:
      - ~/.config/gcloud:/gcloud
    ports:
      - "5100:5100"
    depends_on:
      - postgres
    env_file:
      - path: .env
        required: false
      - path: ./develop/shared/share.env
    environment:
      - EAVE_DB_HOST=postgres
      - EAVE_DB_NAME=eave_dev
      - EAVE_DB_PORT=5132
      - EAVE_DB_USER=app
      - EAVE_DB_PASS=unsafe
      - GOOGLE_APPLICATION_CREDENTIALS=/gcloud/application_default_credentials.json
      - GOOGLE_CLOUD_PROJECT=eavefyi-dev