"""add indexes to gh docs

Revision ID: cd3bd2130990
Revises: e708f76affcb
Create Date: 2023-09-05 23:18:48.577467

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "cd3bd2130990"
down_revision = "e708f76affcb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_github_documents_id"), "github_documents", ["id"], unique=True)
    op.create_index(
        op.f("ix_github_documents_team_id"),
        "github_documents",
        ["team_id", "external_repo_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_github_documents_team_id"), table_name="github_documents")
    op.drop_index(op.f("ix_github_documents_id"), table_name="github_documents")
    # ### end Alembic commands ###
