"""confluence dest update

Revision ID: cb9ab45eb78f
Revises: 8b9901c4cc2c
Create Date: 2023-06-05 15:41:40.328302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cb9ab45eb78f"
down_revision = "8b9901c4cc2c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "confluence_destinations",
        sa.Column("team_id", sa.Uuid(), nullable=False),
    )
    op.create_foreign_key(
        None,
        "confluence_destinations",
        "teams",
        ["team_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
