"""bryanisanidiot

Revision ID: abd2c075bfd8
Revises: 7149db256d39
Create Date: 2023-10-09 20:41:58.316430

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "abd2c075bfd8"
down_revision = "7149db256d39"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(
    #     "ix_forge_installations_forge_app_installation_id",
    #     table_name="forge_installations",
    # )
    # op.drop_table("forge_installations")
    op.add_column(
        "github_repos",
        sa.Column("github_installation_id", sa.Uuid(), nullable=False),
    )
    op.create_foreign_key(
        "github_installation_id_github_installations_id_team_id_fk",
        "github_repos",
        "github_installations",
        ["team_id", "github_installation_id"],
        ["team_id", "id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "github_installation_id_github_installations_id_team_id_fk",
        "github_repos",
        type_="foreignkey",
    )
    op.drop_column("github_repos", "github_installation_id")
    op.create_table(
        "forge_installations",
        sa.Column("team_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "confluence_space_key",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("forge_app_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "forge_app_version",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "forge_app_installation_id",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "forge_app_installer_account_id",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("webtrigger_url", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "created",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], name="forge_installations_team_id_fkey"),
        sa.PrimaryKeyConstraint("forge_app_installation_id", "id", name="forge_installations_pkey"),
    )
    op.create_index(
        "ix_forge_installations_forge_app_installation_id",
        "forge_installations",
        ["forge_app_installation_id"],
        unique=False,
    )
    # ### end Alembic commands ###
