"""add account tracking params

Revision ID: 25534cc72fa4
Revises: 3caea2be815c
Create Date: 2023-05-02 19:11:02.601598

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "25534cc72fa4"
down_revision = "3caea2be815c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accounts", sa.Column("visitor_id", sa.Uuid(), nullable=True)
    )
    op.add_column(
        "accounts",
        sa.Column(
            "opaque_utm_params",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accounts", "opaque_utm_params")
    op.drop_column("accounts", "visitor_id")
    # ### end Alembic commands ###
