"""make more gh_docs cols optional

Revision ID: 790d3912e087
Revises: be558c67008e
Create Date: 2023-09-11 22:17:47.517912

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "790d3912e087"
down_revision = "be558c67008e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "github_documents",
        "status_updated",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column(
        "github_documents",
        "file_path",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.alter_column(
        "github_documents",
        "api_name",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "github_documents",
        "api_name",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "github_documents",
        "file_path",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "github_documents",
        "status_updated",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    # ### end Alembic commands ###
