"""connect table

Revision ID: e4bd5c3ccdc8
Revises: bea023d0efa1
Create Date: 2023-06-01 23:12:25.756007

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e4bd5c3ccdc8"
down_revision = "bea023d0efa1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "connect_installations",
        sa.Column("team_id", sa.Uuid(), nullable=True),
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("(gen_random_uuid())"),
            nullable=False,
        ),
        sa.Column(
            "product",
            sa.Enum("jira", "confluence", name="atlassianproduct"),
            nullable=False,
        ),
        sa.Column("client_key", sa.String(), nullable=False),
        sa.Column("shared_secret", sa.String(), nullable=False),
        sa.Column("base_url", sa.String(), nullable=False),
        sa.Column("atlassian_actor_account_id", sa.String(), nullable=True),
        sa.Column("display_url", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "created",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("product", "client_key", "id"),
    )
    op.create_index(
        op.f("ix_connect_installations_product"),
        "connect_installations",
        ["product", "client_key"],
        unique=True,
    )
    op.drop_index(
        "ix_jira_installations_client_key", table_name="jira_installations"
    )
    op.drop_table("jira_installations")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jira_installations",
        sa.Column("team_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "client_key", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "shared_secret", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "base_url", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "atlassian_actor_account_id",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "display_url", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "description", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
            name="jira_installations_team_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "client_key", "id", name="jira_installations_pkey"
        ),
    )
    op.create_index(
        "ix_jira_installations_client_key",
        "jira_installations",
        ["client_key"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_connect_installations_product"),
        table_name="connect_installations",
    )
    op.drop_table("connect_installations")
    # ### end Alembic commands ###
