"""empty message

Revision ID: f2904b33fe71
Revises: a3cf567b981a
Create Date: 2023-04-16 16:35:11.089296

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f2904b33fe71"
down_revision = "a3cf567b981a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("confluence_destinations")
    op.add_column(
        "atlassian_installations",
        sa.Column("confluence_space", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("atlassian_installations", "confluence_space")
    op.create_table(
        "confluence_destinations",
        sa.Column("team_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("space", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "created",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
            name="confluence_destinations_team_id_fkey",
        ),
        sa.PrimaryKeyConstraint("team_id", "id", name="confluence_destinations_pkey"),
    )
    # ### end Alembic commands ###
