"""delete oauth state table

Revision ID: bfb0a7c92260
Revises: a272e54c46ae
Create Date: 2023-04-03 14:59:30.032579

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "bfb0a7c92260"
down_revision = "a272e54c46ae"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("state", table_name="oauth_states")
    op.drop_table("oauth_states")
    op.drop_index("slack_team_id", table_name="slack_sources")
    op.create_index(
        "slack_team_id_eave_team_idteam_id",
        "slack_sources",
        ["slack_team_id"],
        unique=True,
    )
    op.create_unique_constraint(None, "slack_sources", ["slack_team_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "slack_sources", type_="unique")
    op.drop_index(
        "slack_team_id_eave_team_idteam_id", table_name="slack_sources"
    )
    op.create_index(
        "slack_team_id", "slack_sources", ["team_id"], unique=False
    )
    op.create_table(
        "oauth_states",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("state", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "expire_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="oauth_states_pkey"),
    )
    op.create_index("state", "oauth_states", ["expire_at"], unique=False)
    # ### end Alembic commands ###
