"""remove document reference unique constraint

Revision ID: a4ee5f0e5c49
Revises: 389edb075d5e
Create Date: 2023-05-17 20:51:23.858609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a4ee5f0e5c49"
down_revision = "389edb075d5e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("document_key", table_name="document_references")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "document_key",
        "document_references",
        ["team_id", "document_id"],
        unique=False,
    )
    # ### end Alembic commands ###
