"""add previous access token

Revision ID: ab1d261ea5ed
Revises: abd2c075bfd8
Create Date: 2023-10-10 14:48:24.880498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ab1d261ea5ed"
down_revision = "abd2c075bfd8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accounts",
        sa.Column("previous_access_token", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accounts", "previous_access_token")
    # ### end Alembic commands ###
