"""add gh install id fk to gh repos

Revision ID: 18df005a7979
Revises: 70b7dad6deff
Create Date: 2023-09-28 03:12:23.182097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "18df005a7979"
down_revision = "70b7dad6deff"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "github_repos",
        sa.Column("github_installation_id", sa.String(), nullable=False),
    )
    op.create_foreign_key(
        "github_repos_github_installations_id_fk",
        "github_repos",
        "github_installations",
        ["github_installation_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "github_repos_github_installations_id_fk",
        "github_repos",
        type_="foreignkey",
    )
    op.drop_column("github_repos", "github_installation_id")
    # ### end Alembic commands ###
