"""make fk nullable

Revision ID: 7f2fcd4ee2dc
Revises: d2f7aeadc1bb
Create Date: 2023-10-05 16:42:00.033787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7f2fcd4ee2dc"
down_revision = "d2f7aeadc1bb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_github_documents_team_id"),
        "github_documents",
        ["team_id", "external_repo_id", "pull_request_number"],
        unique=False,
    )
    op.alter_column(
        "github_repos",
        "github_installation_id",
        existing_type=sa.UUID(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "github_repos",
        "github_installation_id",
        existing_type=sa.UUID(),
        nullable=False,
    )
    op.drop_index(op.f("ix_github_documents_team_id"), table_name="github_documents")
    # ### end Alembic commands ###
