"""empty message

Revision ID: cc8f292a5bc3
Revises:
Create Date: 2023-02-16 12:09:52.329496

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "cc8f292a5bc3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_documents_external_id", table_name="documents")
    op.drop_index("ix_documents_external_url", table_name="documents")
    op.drop_table("documents")
    op.drop_index("ix_slack_subscriptions_document_id", table_name="slack_subscriptions")
    op.drop_index("slack_source", table_name="slack_subscriptions")
    op.drop_table("slack_subscriptions")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass
