"""empty message

Revision ID: a3cf567b981a
Revises: 4689f2704a97
Create Date: 2023-04-15 19:30:29.717474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a3cf567b981a"
down_revision = "4689f2704a97"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "atlassian_installations",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("atlassian_cloud_id", sa.String(), nullable=False),
        sa.Column("oauth_token_encoded", sa.String(), nullable=False),
        sa.Column(
            "created",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("team_id", "id"),
        sa.UniqueConstraint("atlassian_cloud_id"),
    )
    op.create_index(
        "eave_team_id_atlassian_team_id",
        "atlassian_installations",
        ["team_id", "atlassian_cloud_id"],
        unique=True,
    )
    op.drop_column("confluence_destinations", "url")
    op.drop_column("confluence_destinations", "api_username")
    op.drop_column("confluence_destinations", "api_key")
    op.add_column(
        "teams",
        sa.Column(
            "beta_whitelisted",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("teams", "beta_whitelisted")
    op.add_column(
        "confluence_destinations",
        sa.Column(
            "api_key", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "confluence_destinations",
        sa.Column(
            "api_username", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "confluence_destinations",
        sa.Column("url", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_index(
        "eave_team_id_atlassian_team_id", table_name="atlassian_installations"
    )
    op.drop_table("atlassian_installations")
    # ### end Alembic commands ###
