"""rename gh install fk

Revision ID: 4d537925ec55
Revises: 68da25b91828
Create Date: 2023-09-28 16:34:25.062206

"""


# revision identifiers, used by Alembic.
revision = "4d537925ec55"
down_revision = "e8115fe8febb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    pass


# def upgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column(
#         "github_repos",
#         sa.Column("github_install_id", sa.String(), nullable=False),
#     )
#     op.drop_constraint(
#         "github_repos_github_installations_id_fk",
#         "github_repos",
#         type_="foreignkey",
#     )
#     op.create_foreign_key(
#         "github_repos_github_installations_github_install_id_fk",
#         "github_repos",
#         "github_installations",
#         ["github_install_id"],
#         ["github_install_id"],
#         ondelete="CASCADE",
#     )
#     op.drop_column("github_repos", "github_installation_id")
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column(
#         "github_repos",
#         sa.Column(
#             "github_installation_id",
#             sa.VARCHAR(),
#             autoincrement=False,
#             nullable=False,
#         ),
#     )
#     op.drop_constraint(
#         "github_repos_github_installations_github_install_id_fk",
#         "github_repos",
#         type_="foreignkey",
#     )
#     op.create_foreign_key(
#         "github_repos_github_installations_id_fk",
#         "github_repos",
#         "github_installations",
#         ["github_installation_id"],
#         ["github_install_id"],
#         ondelete="CASCADE",
#     )
#     op.drop_column("github_repos", "github_install_id")
#     # ### end Alembic commands ###
