"""add org_url to connect installs

Revision ID: a61fd4303d02
Revises: cb9ab45eb78f
Create Date: 2023-06-06 01:35:24.245648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a61fd4303d02"
down_revision = "cb9ab45eb78f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column("atlassian_installations", "confluence_space")
    op.add_column(
        "connect_installations",
        sa.Column("org_url", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###
