"""add github installation

Revision ID: fd592a47b9cc
Revises: 6250b07ae8e8
Create Date: 2023-05-01 04:38:07.887592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fd592a47b9cc"
down_revision = "6250b07ae8e8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "github_installations",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("(gen_random_uuid())"),
            nullable=False,
        ),
        sa.Column("github_install_id", sa.String(), nullable=False),
        sa.Column(
            "created",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("team_id", "id"),
    )
    op.create_index(
        "eave_team_id_github_install_id",
        "github_installations",
        ["team_id", "github_install_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_github_installations_github_install_id"),
        "github_installations",
        ["github_install_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_github_installations_github_install_id"),
        table_name="github_installations",
    )
    op.drop_index("eave_team_id_github_install_id", table_name="github_installations")
    op.drop_table("github_installations")
    # ### end Alembic commands ###
