"""use composite fk gh install id

Revision ID: 19ce49f1a9cf
Revises: 4d537925ec55
Create Date: 2023-10-04 00:07:09.451786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "19ce49f1a9cf"
down_revision = "4d537925ec55"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "github_repos",
        sa.Column("github_installation_id", sa.Uuid(), nullable=False),
    )
    op.drop_constraint(
        "github_repos_github_installations_github_install_id_fk",
        "github_repos",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "github_installation_id_github_installations_id_team_id_fk",
        "github_repos",
        "github_installations",
        ["team_id", "github_installation_id"],
        ["team_id", "id"],
        ondelete="CASCADE",
    )
    op.drop_column("github_repos", "github_install_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "github_repos",
        sa.Column(
            "github_install_id",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(
        "github_installation_id_github_installations_id_team_id_fk",
        "github_repos",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "github_repos_github_installations_github_install_id_fk",
        "github_repos",
        "github_installations",
        ["github_install_id"],
        ["github_install_id"],
        ondelete="CASCADE",
    )
    op.drop_column("github_repos", "github_installation_id")
    # ### end Alembic commands ###
