"""auth_models

Revision ID: b962738244f6
Revises: 6a14ca341474
Create Date: 2023-04-26 07:44:36.036331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b962738244f6"
down_revision = "6a14ca341474"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "github_installations",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("(gen_random_uuid())"),
            nullable=False,
        ),
        sa.Column("github_install_id", sa.String(), nullable=False),
        sa.Column(
            "created",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("team_id", "id"),
        sa.UniqueConstraint("github_install_id"),
    )
    op.create_index(
        "eave_team_id_github_install_id",
        "github_installations",
        ["team_id", "github_install_id"],
        unique=True,
    )
    op.create_table(
        "auth_tokens",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("(gen_random_uuid())"),
            nullable=False,
        ),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("access_token", sa.String(), nullable=False),
        sa.Column("refresh_token", sa.String(), nullable=False),
        sa.Column("jti", sa.String(), nullable=False),
        sa.Column("iss", sa.String(), nullable=False),
        sa.Column("aud", sa.String(), nullable=False),
        sa.Column("expires", sa.DateTime(), nullable=False),
        sa.Column("invalidated", sa.DateTime(), nullable=True),
        sa.Column(
            "created",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["team_id", "account_id"],
            ["accounts.team_id", "accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("team_id", "id"),
    )
    op.create_index(
        op.f("ix_auth_tokens_access_token"),
        "auth_tokens",
        ["access_token"],
        unique=True,
    )
    op.create_index(
        op.f("ix_auth_tokens_refresh_token"),
        "auth_tokens",
        ["refresh_token"],
        unique=True,
    )
    op.create_index(
        "token_pair",
        "auth_tokens",
        ["access_token", "refresh_token"],
        unique=True,
    )
    op.create_index(
        op.f("ix_accounts_auth_provider"),
        "accounts",
        ["auth_provider", "auth_id", "oauth_token"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_accounts_auth_provider"), table_name="accounts")
    op.drop_index("token_pair", table_name="auth_tokens")
    op.drop_index(
        op.f("ix_auth_tokens_refresh_token"), table_name="auth_tokens"
    )
    op.drop_index(
        op.f("ix_auth_tokens_access_token"), table_name="auth_tokens"
    )
    op.drop_table("auth_tokens")
    op.drop_index(
        "eave_team_id_github_install_id", table_name="github_installations"
    )
    op.drop_table("github_installations")
    # ### end Alembic commands ###
