"""github owner login

Revision ID: 7149db256d39
Revises: 6cf1ca6c1e4d
Create Date: 2023-10-06 09:49:27.478517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7149db256d39"
down_revision = "6cf1ca6c1e4d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "github_installations",
        sa.Column("github_owner_login", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("github_installations", "github_owner_login")
    # ### end Alembic commands ###
