"""empty message

Revision ID: e8115fe8febb
Revises: 23d85d98202d
Create Date: 2023-06-09 18:18:29.426022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e8115fe8febb"
down_revision = "23d85d98202d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_connect_installations_team_id"),
        "connect_installations",
        ["team_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_connect_installations_team_id"),
        table_name="connect_installations",
    )
    # ### end Alembic commands ###
