"""slack oauth state store

Revision ID: cb5b68318224
Revises: 49afa1d62242
Create Date: 2023-03-31 17:33:42.115333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cb5b68318224"
down_revision = "49afa1d62242"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oauth_states",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("expire_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("state", "oauth_states", ["expire_at"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("state", table_name="oauth_states")
    op.drop_table("oauth_states")
    # ### end Alembic commands ###
