"""add github_repos display_name

Revision ID: 70b7dad6deff
Revises: 3b91c04af103
Create Date: 2023-09-22 21:48:15.839146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "70b7dad6deff"
down_revision = "3b91c04af103"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "github_repos", sa.Column("display_name", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("github_repos", "display_name")
    # ### end Alembic commands ###
