"""

Revision ID: 389edb075d5e
Revises: 271e6339d054
Create Date: 2023-05-15 15:55:19.112289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "389edb075d5e"
down_revision = "271e6339d054"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resource_mutexes",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("(gen_random_uuid())"),
            nullable=False,
        ),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("resource_id"),
    )
    op.add_column(
        "slack_sources",
        sa.Column("bot_token_exp", sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("slack_sources", "bot_token_exp")
    op.drop_table("resource_mutexes")
    # ### end Alembic commands ###
