"""rm redundent gh_repos id

Revision ID: 0cbb232d24bd
Revises: eea9f20b2aca
Create Date: 2023-09-01 17:02:52.151538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0cbb232d24bd"
down_revision = "eea9f20b2aca"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("github_repos", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "github_repos",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
