"""add id back to gh_docs table

Revision ID: 3b91c04af103
Revises: 790d3912e087
Create Date: 2023-09-11 23:30:34.297937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3b91c04af103"
down_revision = "790d3912e087"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "github_documents",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("(gen_random_uuid())"),
            nullable=False,
        ),
    )
    op.create_index(op.f("ix_github_documents_id"), "github_documents", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_github_documents_id"), table_name="github_documents")
    op.drop_column("github_documents", "id")
    # ### end Alembic commands ###
