"""add table to track job status

Revision ID: 7cc36d129246
Revises: 8ad217a7c1d3
Create Date: 2023-11-14 19:44:45.319471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7cc36d129246"
down_revision = "8ad217a7c1d3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_documentation_jobs",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("(gen_random_uuid())"),
            nullable=False,
        ),
        sa.Column("github_repo_id", sa.Uuid(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("last_result", sa.String(), server_default="none", nullable=False),
        sa.Column(
            "created",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["github_repo_id"],
            ["github_repos.id"],
            name="github_repos_id_fk",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint(
            "team_id",
            "github_repo_id",
            "id",
            name="pk_team_id_github_repo_id_id",
        ),
    )
    op.create_index(
        "team_id_github_repo_id_unique_idx",
        "api_documentation_jobs",
        ["team_id", "github_repo_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "team_id_github_repo_id_unique_idx",
        table_name="api_documentation_jobs",
    )
    op.drop_table("api_documentation_jobs")
    # ### end Alembic commands ###
