"""gh install optional team id

Revision ID: e04a9002c582
Revises: ab1d261ea5ed
Create Date: 2023-10-24 22:06:02.382257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e04a9002c582"
down_revision = "ab1d261ea5ed"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("github_installations", sa.Column("install_flow_state", sa.String(), nullable=True))
    op.create_unique_constraint("id_unique", "github_installations", ["id"])
    op.drop_constraint(
        "github_installation_id_github_installations_id_team_id_fk",
        "github_repos",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "github_installation_id_github_installations_fk",
        "github_repos",
        "github_installations",
        ["github_installation_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "github_installations_pkey",
        "github_installations",
        "primary",
    )
    op.create_primary_key(
        "pk_github_installations_id",
        "github_installations",
        ["id"],
    )
    op.alter_column(
        "github_installations",
        "team_id",
        existing_type=sa.UUID(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("github_installations", "install_flow_state")
    op.alter_column(
        "github_installations",
        "team_id",
        existing_type=sa.UUID(),
        nullable=False,
    )
    op.drop_constraint(
        "pk_github_installations_id",
        "github_installations",
        "primary",
    )
    op.create_primary_key("github_installations_pkey", "github_installations", ["team_id", "id"])
    op.drop_constraint(
        "github_installation_id_github_installations_fk",
        "github_repos",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "github_installation_id_github_installations_id_team_id_fk",
        "github_repos",
        "github_installations",
        ["team_id", "github_installation_id"],
        ["team_id", "id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("id_unique", "github_installations", type_="unique")
    # ### end Alembic commands ###
