"""

Revision ID: 6250b07ae8e8
Revises: 46ff1f8026ca
Create Date: 2023-04-29 22:44:30.189949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6250b07ae8e8"
down_revision = "46ff1f8026ca"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accounts", sa.Column("refresh_token", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accounts", "refresh_token")
    # ### end Alembic commands ###
