"""add composite index to gh_repos

Revision ID: e708f76affcb
Revises: 0cbb232d24bd
Create Date: 2023-09-01 17:31:43.262843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e708f76affcb"
down_revision = "0cbb232d24bd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_github_repos_team_id"),
        "github_repos",
        ["team_id", "external_repo_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_github_repos_team_id"), table_name="github_repos")
    # ### end Alembic commands ###
