"""add gh repos and documents tables

Revision ID: eea9f20b2aca
Revises: e8115fe8febb
Create Date: 2023-08-31 23:52:56.130519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eea9f20b2aca"
down_revision = "e8115fe8febb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "github_repos",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("(gen_random_uuid())"),
            nullable=False,
        ),
        sa.Column("external_repo_id", sa.String(), nullable=False),
        sa.Column("api_documentation_state", sa.String(), nullable=True),
        sa.Column(
            "inline_code_documentation_state", sa.String(), nullable=True
        ),
        sa.Column(
            "architecture_documentation_state", sa.String(), nullable=True
        ),
        sa.Column(
            "created",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("team_id", "id", "external_repo_id"),
        sa.UniqueConstraint("external_repo_id"),
    )
    op.create_table(
        "github_documents",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("(gen_random_uuid())"),
            nullable=False,
        ),
        sa.Column("external_repo_id", sa.String(), nullable=False),
        sa.Column("pull_request_number", sa.Integer(), nullable=False),
        sa.Column(
            "status", sa.String(), server_default="processing", nullable=False
        ),
        sa.Column("status_updated", sa.DateTime(), nullable=True),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column("api_name", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column(
            "created",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["external_repo_id"],
            ["github_repos.external_repo_id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("team_id", "id", "external_repo_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("github_documents")
    op.drop_table("github_repos")
    # ### end Alembic commands ###
