"""correct gh repo id fk

Revision ID: e517ccd21712
Revises: 7cc36d129246
Create Date: 2023-11-15 21:53:59.163185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e517ccd21712"
down_revision = "7cc36d129246"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "github_repo_id_github_repos_id_team_id_fk",
        "api_documentation_jobs",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "github_repo_id_github_repos_id_team_id_fk",
        "api_documentation_jobs",
        "github_repos",
        ["team_id", "github_repo_id"],
        ["team_id", "id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "github_repo_id_github_repos_id_team_id_fk",
        "api_documentation_jobs",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "github_repo_id_github_repos_id_team_id_fk",
        "api_documentation_jobs",
        "github_repos",
        ["github_repo_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
