"""forge tables

Revision ID: b2eb47841833
Revises: 920f9d3ede4c
Create Date: 2023-05-29 03:01:23.901988

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b2eb47841833"
down_revision = "920f9d3ede4c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "forge_installations",
        sa.Column("team_id", sa.Uuid(), nullable=True),
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("(gen_random_uuid())"),
            nullable=False,
        ),
        sa.Column("confluence_space_key", sa.String(), nullable=True),
        sa.Column("forge_app_id", sa.String(), nullable=False),
        sa.Column("forge_app_version", sa.String(), nullable=False),
        sa.Column("forge_app_installation_id", sa.String(), nullable=False),
        sa.Column("forge_app_installer_account_id", sa.String(), nullable=False),
        sa.Column("webtrigger_url", sa.String(), nullable=False),
        sa.Column(
            "created",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("forge_app_installation_id", "id"),
    )
    op.create_index(
        op.f("ix_forge_installations_forge_app_installation_id"),
        "forge_installations",
        ["forge_app_installation_id"],
        unique=True,
    )
    op.drop_index("ix_access_requests_email", table_name="access_requests")
    op.drop_index("ix_access_requests_visitor_id", table_name="access_requests")
    op.drop_table("access_requests")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_requests",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("visitor_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("opaque_input", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="access_requests_pkey"),
    )
    op.create_index(
        "ix_access_requests_visitor_id",
        "access_requests",
        ["visitor_id"],
        unique=False,
    )
    op.create_index("ix_access_requests_email", "access_requests", ["email"], unique=False)
    op.drop_index(
        op.f("ix_forge_installations_forge_app_installation_id"),
        table_name="forge_installations",
    )
    op.drop_table("forge_installations")
    # ### end Alembic commands ###
