"""add slacksource bot cols

Revision ID: 4689f2704a97
Revises: bfb0a7c92260
Create Date: 2023-04-04 21:50:06.494540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4689f2704a97"
down_revision = "bfb0a7c92260"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "slack_sources", sa.Column("bot_token", sa.String(), nullable=False)
    )
    op.add_column(
        "slack_sources", sa.Column("bot_id", sa.String(), nullable=False)
    )
    op.drop_index(
        "slack_team_id_eave_team_idteam_id", table_name="slack_sources"
    )
    op.create_index(
        "slack_team_id_eave_team_id",
        "slack_sources",
        ["team_id", "slack_team_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("slack_team_id_eave_team_id", table_name="slack_sources")
    op.create_index(
        "slack_team_id_eave_team_idteam_id",
        "slack_sources",
        ["slack_team_id"],
        unique=False,
    )
    op.drop_column("slack_sources", "bot_id")
    op.drop_column("slack_sources", "bot_token")
    # ### end Alembic commands ###
