"""add bot refresh token

Revision ID: 3caea2be815c
Revises: 6250b07ae8e8
Create Date: 2023-04-30 23:22:36.581163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3caea2be815c"
down_revision = "6250b07ae8e8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "slack_sources",
        sa.Column("bot_refresh_token", sa.String(), nullable=True),
    )
    op.drop_column("slack_sources", "bot_id")
    op.drop_column("slack_sources", "bot_user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "slack_sources",
        sa.Column(
            "bot_user_id", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "slack_sources",
        sa.Column("bot_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("slack_sources", "bot_refresh_token")
    # ### end Alembic commands ###
