"""auth_models

Revision ID: 46ff1f8026ca
Revises: 6a14ca341474
Create Date: 2023-04-29 20:09:31.481754

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "46ff1f8026ca"
down_revision = "6a14ca341474"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_tokens",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("(gen_random_uuid())"),
            nullable=False,
        ),
        sa.Column("access_token_hashed", sa.String(), nullable=False),
        sa.Column("refresh_token_hashed", sa.String(), nullable=False),
        sa.Column("jti", sa.String(), nullable=False),
        sa.Column("iss", sa.String(), nullable=False),
        sa.Column("aud", sa.String(), nullable=False),
        sa.Column("expires", sa.DateTime(), nullable=False),
        sa.Column("invalidated", sa.DateTime(), nullable=True),
        sa.Column(
            "created",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["team_id", "account_id"],
            ["accounts.team_id", "accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("team_id", "account_id", "id"),
    )
    op.create_index(
        op.f("ix_auth_tokens_access_token_hashed"),
        "auth_tokens",
        ["access_token_hashed"],
        unique=True,
    )
    op.create_index(
        op.f("ix_auth_tokens_refresh_token_hashed"),
        "auth_tokens",
        ["refresh_token_hashed"],
        unique=True,
    )
    op.create_index(
        "jwt_claims",
        "auth_tokens",
        ["access_token_hashed", "aud", "iss", "expires"],
        unique=False,
    )
    op.create_index(
        "token_pair",
        "auth_tokens",
        ["access_token_hashed", "refresh_token_hashed"],
        unique=True,
    )
    op.create_index(
        op.f("ix_accounts_auth_provider"),
        "accounts",
        ["auth_provider", "auth_id", "oauth_token"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_accounts_auth_provider"), table_name="accounts")
    op.drop_index("token_pair", table_name="auth_tokens")
    op.drop_index("jwt_claims", table_name="auth_tokens")
    op.drop_index(op.f("ix_auth_tokens_refresh_token_hashed"), table_name="auth_tokens")
    op.drop_index(op.f("ix_auth_tokens_access_token_hashed"), table_name="auth_tokens")
    op.drop_table("auth_tokens")
    # ### end Alembic commands ###
