"""add slacksource table

Revision ID: 49afa1d62242
Revises: b806fa046c93
Create Date: 2023-03-31 11:27:08.923662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "49afa1d62242"
down_revision = "b806fa046c93"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "slack_sources",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("slack_team_id", sa.String(), nullable=False),
        sa.Column(
            "created",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("team_id", "id"),
    )
    op.create_index("slack_team_id", "slack_sources", ["team_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("slack_team_id", table_name="slack_sources")
    op.drop_table("slack_sources")
    # ### end Alembic commands ###
