"""add emails to accounts table

Revision ID: e66762912ba4
Revises: a4ee5f0e5c49
Create Date: 2023-05-23 20:02:56.687214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e66762912ba4"
down_revision = "a4ee5f0e5c49"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("accounts", sa.Column("email", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accounts", "email")
    # ### end Alembic commands ###
