"""rm unnecessary index on gh repos

Revision ID: be558c67008e
Revises: 6f1cdfb6ee8b
Create Date: 2023-09-07 22:35:11.830780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "be558c67008e"
down_revision = "6f1cdfb6ee8b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_github_repos_team_id", table_name="github_repos")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_github_repos_team_id",
        "github_repos",
        ["team_id", "external_repo_id"],
        unique=False,
    )
    # ### end Alembic commands ###
