"""make pr number optional

Revision ID: 3caaacc6e36f
Revises: cd3bd2130990
Create Date: 2023-09-06 00:21:19.183941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3caaacc6e36f"
down_revision = "cd3bd2130990"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "github_documents",
        "pull_request_number",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "github_documents",
        "pull_request_number",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    # ### end Alembic commands ###
