"""add identifiers to installation tables

Revision ID: 920f9d3ede4c
Revises: e66762912ba4
Create Date: 2023-05-23 21:50:39.850888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "920f9d3ede4c"
down_revision = "e66762912ba4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "atlassian_installations",
        sa.Column("atlassian_site_name", sa.String(), nullable=True),
    )
    op.add_column(
        "slack_sources",
        sa.Column("slack_team_name", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("slack_sources", "slack_team_name")
    op.drop_column("atlassian_installations", "atlassian_site_name")
    # ### end Alembic commands ###
