"""update slack source

Revision ID: ec5163a66313
Revises: 4689f2704a97
Create Date: 2023-04-09 09:33:57.617906

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ec5163a66313"
down_revision = "4689f2704a97"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("slack_sources", sa.Column("bot_user_id", sa.String(), nullable=True))
    op.drop_constraint("slack_sources_slack_team_id_key", "slack_sources", type_="unique")
    op.create_index(
        op.f("ix_slack_sources_slack_team_id"),
        "slack_sources",
        ["slack_team_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_slack_sources_slack_team_id"), table_name="slack_sources")
    op.create_unique_constraint("slack_sources_slack_team_id_key", "slack_sources", ["slack_team_id"])
    op.drop_column("slack_sources", "bot_user_id")
    # ### end Alembic commands ###
