"""rm unnecessary id col from gh doc

Revision ID: 6f1cdfb6ee8b
Revises: 3caaacc6e36f
Create Date: 2023-09-07 22:08:39.321488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6f1cdfb6ee8b"
down_revision = "3caaacc6e36f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_github_documents_id", table_name="github_documents")
    op.drop_index("ix_github_documents_team_id", table_name="github_documents")
    op.drop_column("github_documents", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "github_documents",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_index(
        "ix_github_documents_team_id",
        "github_documents",
        ["team_id", "external_repo_id"],
        unique=False,
    )
    op.create_index(
        "ix_github_documents_id", "github_documents", ["id"], unique=False
    )
    # ### end Alembic commands ###
