"""add organizer id to eventbrite events

Revision ID: c0e9bbcf9279
Revises: d9e27d608154
Create Date: 2024-12-16 07:44:33.498112

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c0e9bbcf9279"
down_revision = "d9e27d608154"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("eventbrite_events", sa.Column("eventbrite_organizer_id", sa.String(), nullable=False))
    op.create_index(
        op.f("ix_eventbrite_events_eventbrite_organizer_id"),
        "eventbrite_events",
        ["eventbrite_organizer_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_eventbrite_events_eventbrite_organizer_id"), table_name="eventbrite_events")
    op.drop_column("eventbrite_events", "eventbrite_organizer_id")
    # ### end Alembic commands ###
