"""outing fk instead of survey fk on bookings

Revision ID: 87365f91d83a
Revises: 06d0d71488bc
Create Date: 2024-12-17 19:40:53.412780

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "87365f91d83a"
down_revision = "06d0d71488bc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bookings", sa.Column("outing_id", sa.Uuid(), nullable=True))
    op.drop_index("ix_bookings_survey_id", table_name="bookings")
    op.create_index(op.f("ix_bookings_outing_id"), "bookings", ["outing_id"], unique=False)
    op.drop_constraint("bookings_survey_id_fkey", "bookings", type_="foreignkey")
    op.create_foreign_key(None, "bookings", "outings", ["outing_id"], ["id"], ondelete="SET NULL")
    op.drop_column("bookings", "survey_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
