"""remove github installations

Revision ID: f2b74aeb9db0
Revises: da850e92c619
Create Date: 2024-04-24 19:23:24.312349

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "f2b74aeb9db0"
down_revision = "da850e92c619"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("github_installations")
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
