"""change address types

Revision ID: 786f1ff4f5bd
Revises: d4a94d8ee453
Create Date: 2024-12-03 16:55:15.544494

"""

import sqlalchemy as sa
from alembic import op

from eave.core.orm.util.user_defined_column_types import AddressFieldsColumnType

# revision identifiers, used by Alembic.
revision = "786f1ff4f5bd"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("booking_activity_templates", "address")
    op.drop_column("booking_reservation_templates", "address")
    op.drop_column("activities", "address")

    op.add_column(
        "booking_activity_templates",
        sa.Column("address", AddressFieldsColumnType(), nullable=False),
    )
    op.add_column(
        "booking_reservation_templates",
        sa.Column("address", AddressFieldsColumnType(), nullable=False),
    )
    op.add_column(
        "activities",
        sa.Column("address", AddressFieldsColumnType(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
