"""add metabase instance

Revision ID: da850e92c619
Revises: 6224ceb2128c
Create Date: 2024-03-20 20:51:43.706627

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "da850e92c619"
down_revision = "6224ceb2128c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "metabase_instances",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("(gen_random_uuid())"),
            nullable=False,
        ),
        sa.Column("jwt_signing_key", sa.String(), nullable=True),
        sa.Column("route_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("team_id", "id", name="pk_metabase_instances_team_id_id"),
    )
    op.create_unique_constraint("gh_id_unique", "github_installations", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("gh_id_unique", "github_installations", type_="unique")
    op.drop_table("metabase_instances")
    # ### end Alembic commands ###
