"""onboarding_form_submission

Revision ID: b07dba53d032
Revises: 954f65ef78c1
Create Date: 2024-07-31 00:03:16.596900

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b07dba53d032"
down_revision = "954f65ef78c1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "onboarding_submissions",
        sa.Column("id", sa.Uuid(), server_default=sa.text("(gen_random_uuid())"), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column(
            "languages", postgresql.ARRAY(sa.String(), dimensions=1), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column(
            "platforms", postgresql.ARRAY(sa.String(), dimensions=1), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column(
            "frameworks", postgresql.ARRAY(sa.String(), dimensions=1), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column(
            "databases", postgresql.ARRAY(sa.String(), dimensions=1), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column(
            "third_party_libs",
            postgresql.ARRAY(sa.String(), dimensions=1),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("created", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("team_id", "id", name="pk_onboarding_submissions_team_id_id"),
    )
    op.add_column("teams", sa.Column("dashboard_access", sa.Boolean(), server_default=sa.text("true"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("teams", "dashboard_access")
    op.drop_table("onboarding_submissions")
    # ### end Alembic commands ###
