"""add default dashboard id

Revision ID: 052d73b4edda
Revises: c45e0d03826a
Create Date: 2024-05-10 15:53:33.531413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "052d73b4edda"
down_revision = "c45e0d03826a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("metabase_instances", sa.Column("default_dashboard_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("metabase_instances", "default_dashboard_id")
    # ### end Alembic commands ###
