"""evergreen updates

Revision ID: b0e333d06aa9
Revises: b8d7628fd43a
Create Date: 2024-12-24 23:17:30.713498

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b0e333d06aa9"
down_revision = "b8d7628fd43a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("eventbrite_events", sa.Column("google_place_id", sa.String(), nullable=True))
    op.add_column("evergreen_activities", sa.Column("google_place_id", sa.String(), nullable=True))
    op.drop_column("evergreen_activity_ticket_types", "description")
    op.add_column("weekly_schedules", sa.Column("minute_spans_local", postgresql.INT4MULTIRANGE(), nullable=False))
    op.drop_column("weekly_schedules", "wednesday")
    op.drop_column("weekly_schedules", "monday")
    op.drop_column("weekly_schedules", "thursday")
    op.drop_column("weekly_schedules", "friday")
    op.drop_column("weekly_schedules", "saturday")
    op.drop_column("weekly_schedules", "sunday")
    op.drop_column("weekly_schedules", "tuesday")
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
