"""update allowed origins to array

Revision ID: 34ac25ae3755
Revises: 052d73b4edda
Create Date: 2024-05-27 16:33:53.915813

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "34ac25ae3755"
down_revision = "052d73b4edda"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "teams",
        sa.Column(
            "allowed_origins",
            postgresql.ARRAY(sa.String(), dimensions=1),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
    )
    op.drop_column("teams", "allowed_origins_csv")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("teams", sa.Column("allowed_origins_csv", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column("teams", "allowed_origins")
    # ### end Alembic commands ###
