"""add metabase instance state

Revision ID: 954f65ef78c1
Revises: 34ac25ae3755
Create Date: 2024-07-16 20:21:39.395110

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "954f65ef78c1"
down_revision = "34ac25ae3755"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("metabase_instances", sa.Column("state", sa.Integer(), server_default=sa.text("1"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("metabase_instances", "state")
    # ### end Alembic commands ###
