"""eventbrite table updates

Revision ID: 9e092e156e7e
Revises: 87365f91d83a
Create Date: 2024-12-18 22:59:15.601991

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9e092e156e7e"
down_revision = "87365f91d83a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_booking_activity_templates_start_time_utc"),
        "booking_activity_templates",
        ["start_time_utc"],
        unique=False,
    )
    op.create_index(
        op.f("ix_booking_reservation_templates_start_time_utc"),
        "booking_reservation_templates",
        ["start_time_utc"],
        unique=False,
    )
    op.add_column("eventbrite_events", sa.Column("end_time_utc", sa.DateTime(), nullable=True))
    op.add_column("eventbrite_events", sa.Column("min_cost_cents", sa.Integer(), nullable=True))
    op.add_column("eventbrite_events", sa.Column("start_time_utc", postgresql.TIMESTAMP(timezone=True), nullable=False))
    op.create_index(op.f("ix_eventbrite_events_start_time_utc"), "eventbrite_events", ["start_time_utc"], unique=False)
    op.drop_column("eventbrite_events", "time_range_utc")
    op.create_index(op.f("ix_outing_activities_start_time_utc"), "outing_activities", ["start_time_utc"], unique=False)
    op.create_index(
        op.f("ix_outing_reservations_start_time_utc"), "outing_reservations", ["start_time_utc"], unique=False
    )
    op.create_index(op.f("ix_surveys_start_time_utc"), "surveys", ["start_time_utc"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
