"""add join tables

Revision ID: 0edbd263584c
Revises: 0975a117f2f2
Create Date: 2024-12-15 01:29:35.086430

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0edbd263584c"
down_revision = "0975a117f2f2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_images",
        sa.Column("activity_id", sa.Uuid(), nullable=True),
        sa.Column("image_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["activity_id"], ["activities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["image_id"], ["images.id"], ondelete="CASCADE"),
    )
    op.create_table(
        "account_bookings",
        sa.Column("booking_id", sa.Uuid(), nullable=True),
        sa.Column("account_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["booking_id"], ["bookings.id"], ondelete="CASCADE"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
