"""add booking state

Revision ID: 06d0d71488bc
Revises: d9e27d608154
Create Date: 2024-12-16 16:35:13.105460

"""

import sqlalchemy as sa
from alembic import op

from eave.core.orm.booking import BookingStateColumnType

# revision identifiers, used by Alembic.
revision = "06d0d71488bc"
down_revision = "d9e27d608154"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bookings",
        sa.Column("state", BookingStateColumnType(), server_default="INITIATED", nullable=False),
    )
    op.alter_column("bookings", "reserver_details_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column("bookings", "survey_id", existing_type=sa.UUID(), nullable=True)
    op.add_column("eventbrite_events", sa.Column("eventbrite_organizer_id", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_eventbrite_events_eventbrite_organizer_id"),
        "eventbrite_events",
        ["eventbrite_organizer_id"],
        unique=False,
    )
    op.drop_constraint(
        "stripe_payment_intent_references_outing_id_fkey", "stripe_payment_intent_references", type_="foreignkey"
    )
    op.drop_column("stripe_payment_intent_references", "outing_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
