"""nullable alt

Revision ID: 1e6b5745bb0e
Revises: b0e333d06aa9
Create Date: 2024-12-24 23:43:04.256526

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1e6b5745bb0e"
down_revision = "b0e333d06aa9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("images", "alt", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
