"""add more data to templates

Revision ID: d720891e5e6b
Revises: cd683ffbbbd5
Create Date: 2024-12-05 22:47:30.974933

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d720891e5e6b"
down_revision = "cd683ffbbbd5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("booking_activity_templates", sa.Column("source_id", sa.String(), nullable=False))
    op.add_column("booking_activity_templates", sa.Column("source", sa.String(), nullable=False))
    op.add_column("booking_activity_templates", sa.Column("activity_photo_uri", sa.String(), nullable=True))
    op.add_column("booking_reservation_templates", sa.Column("source_id", sa.String(), nullable=False))
    op.add_column("booking_reservation_templates", sa.Column("source", sa.String(), nullable=False))
    op.add_column("booking_reservation_templates", sa.Column("reservation_photo_uri", sa.String(), nullable=True))
    op.add_column("bookings", sa.Column("account_id", sa.Uuid(), nullable=False))
    op.create_index("account_id_booking_index", "bookings", ["account_id"], unique=False)
    op.create_foreign_key("accounts_booking_fk", "bookings", "accounts", ["account_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("accounts_booking_fk", "bookings", type_="foreignkey")
    op.drop_index("account_id_booking_index", table_name="bookings")
    op.drop_column("bookings", "account_id")
    op.drop_column("booking_reservation_templates", "reservation_photo_uri")
    op.drop_column("booking_reservation_templates", "source")
    op.drop_column("booking_reservation_templates", "source_id")
    op.drop_column("booking_activity_templates", "activity_photo_uri")
    op.drop_column("booking_activity_templates", "source")
    op.drop_column("booking_activity_templates", "source_id")
    # ### end Alembic commands ###
