"""update eventbrite events

Revision ID: d9e27d608154
Revises: 0edbd263584c
Create Date: 2024-12-16 05:04:31.838997

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d9e27d608154"
down_revision = "0edbd263584c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("eventbrite_events", sa.Column("max_cost_cents", sa.Integer(), nullable=True))
    op.drop_column("eventbrite_events", "cost_cents_range")
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
