"""unique team id onboarding submission

Revision ID: 508990ea57b5
Revises: 319ed3b587bc
Create Date: 2024-09-27 21:55:30.832543

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "508990ea57b5"
down_revision = "319ed3b587bc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("submission_unique_team_id", "onboarding_submissions", ["team_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("submission_unique_team_id", "onboarding_submissions", type_="unique")
    # ### end Alembic commands ###
