"""update metabase instance orm

Revision ID: c45e0d03826a
Revises: f2b74aeb9db0
Create Date: 2024-05-07 19:07:33.397140

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c45e0d03826a"
down_revision = "f2b74aeb9db0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("metabase_instances", sa.Column("instance_id", sa.String(), nullable=False))
    op.alter_column("metabase_instances", "jwt_signing_key", existing_type=sa.VARCHAR(), nullable=False)
    op.create_unique_constraint(None, "metabase_instances", ["instance_id"])
    op.drop_column("metabase_instances", "route_id")
    op.add_column("teams", sa.Column("allowed_origins_csv", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
