"""

Revision ID: 769660a19595
Revises: 9e092e156e7e
Create Date: 2024-12-19 21:13:27.914360

"""

import sqlalchemy as sa
from alembic import op

from eave.core.orm.util.user_defined_column_types import OutingBudgetColumnType

# revision identifiers, used by Alembic.
revision = "769660a19595"
down_revision = "9e092e156e7e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("outing_activities_id_key", "outing_activities", type_="unique")
    op.drop_constraint("outing_reservations_id_key", "outing_reservations", type_="unique")
    op.alter_column("outings", "survey_id", existing_type=sa.UUID(), nullable=True)
    op.drop_constraint("outings_survey_id_fkey", "outings", type_="foreignkey")
    op.create_foreign_key(None, "outings", "surveys", ["survey_id"], ["id"], ondelete="SET NULL")

    op.drop_column(table_name="surveys", column_name="budget")

    op.add_column(
        "surveys",
        sa.Column("budget", OutingBudgetColumnType(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
