"""add min-max to evergreen ticket type orm

Revision ID: fd25910f1a7a
Revises: 1e6b5745bb0e
Create Date: 2024-12-31 20:47:57.946503

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fd25910f1a7a"
down_revision = "1e6b5745bb0e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("evergreen_activity_ticket_types", sa.Column("max_base_cost_cents", sa.Integer(), nullable=False))
    op.add_column("evergreen_activity_ticket_types", sa.Column("min_base_cost_cents", sa.Integer(), nullable=False))

    # migrate data before dropping column
    # all existing data doesnt have a cost range, so the min cost and max cost should be the same
    op.execute(
        "UPDATE evergreen_activity_ticket_types SET max_base_cost_cents = base_cost_cents, min_base_cost_cents = base_cost_cents"
    )

    op.drop_column("evergreen_activity_ticket_types", "base_cost_cents")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "evergreen_activity_ticket_types",
        sa.Column("base_cost_cents", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("evergreen_activity_ticket_types", "min_base_cost_cents")
    op.drop_column("evergreen_activity_ticket_types", "max_base_cost_cents")
    # ### end Alembic commands ###
