"""onboarding_form_submission

Revision ID: 510ca3cb61e9
Revises: 954f65ef78c1
Create Date: 2024-07-24 17:48:55.129659

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "510ca3cb61e9"
down_revision = "954f65ef78c1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "onboarding_submissions",
        sa.Column("id", sa.Uuid(), server_default=sa.text("(gen_random_uuid())"), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("response_data", sa.JSON(), nullable=False),
        sa.Column("created", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("team_id", "id", name="pk_onboarding_submissions_team_id_id"),
    )
    op.add_column("teams", sa.Column("dashboard_access", sa.Boolean(), server_default=sa.text("true"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("teams", "dashboard_access")
    op.drop_table("onboarding_submissions")
    # ### end Alembic commands ###
