"""link booking to survey

Revision ID: d1b7653758e3
Revises: e2fcb2a27715
Create Date: 2024-12-13 23:53:35.650004

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d1b7653758e3"
down_revision = "e2fcb2a27715"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bookings", sa.Column("survey_id", sa.Uuid(), nullable=False))
    op.create_foreign_key("surveys_booking_fk", "bookings", "surveys", ["survey_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("surveys_booking_fk", "bookings", type_="foreignkey")
    op.drop_column("bookings", "survey_id")
    # ### end Alembic commands ###
