"""add data collector config

Revision ID: 319ed3b587bc
Revises: b07dba53d032
Create Date: 2024-09-11 17:51:40.426799

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "319ed3b587bc"
down_revision = "b07dba53d032"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_collector_configs",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("(gen_random_uuid())"), nullable=False),
        sa.Column("primary_key_patterns", postgresql.ARRAY(sa.String(), dimensions=1), nullable=False),
        sa.Column("foreign_key_patterns", postgresql.ARRAY(sa.String(), dimensions=1), nullable=False),
        sa.Column("user_table_name_patterns", postgresql.ARRAY(sa.String(), dimensions=1), nullable=False),
        sa.Column("created", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("team_id", "id", name="pk_data_collector_configs_team_id_id"),
        sa.UniqueConstraint("team_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("data_collector_configs")
    # ### end Alembic commands ###
