services:
  postgres:
    build: postgres
    ports:
      - "5433:5432"
    volumes:
      - .pgdata:/var/lib/postgresql/data
    env_file:
      - share.postgres.env
      - .env

  metabase:
    image: metabase/metabase-enterprise:latest
    ports:
      - "5400:3000"
    depends_on:
      - postgres
    env_file:
      - share.metabase.env
      - .env
