# Configure kubernetes provider with Oauth2 access token.
# https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/client_config
# This fetches a new token, which will expire in 1 hour.
data "google_client_config" "default" {}

data "google_project" "default" {}

data "google_project" "staging" {
  # This is needed for granting the Staging Thoropass Integration service account the org thoropass role.
  # Because the organization configuration is managed by the
  project_id = "eave-staging"
}

data "google_compute_backend_service" "gateways" {
  for_each = {
    # These names are generated by Google Cloud from Kubernetes Gateway configs.
    "admin" = "gkegw1-pl44-eave-admin-80-x6dbra8rr4l6"
    "core_api_iap" = "gkegw1-pl44-eave-core-api-iap-80-y37b90pplt9n"
  }
  name = each.value
}
