resource "google_iap_brand" "project" {
  application_title = "Eave"
  support_email     = "support@eave.fyi"
}

resource "google_iap_client" "default" {
  brand        = google_iap_brand.project.id
  display_name = "Default IAP Client"
}

resource "google_iap_settings" "admin_gw" {
  # FIXME: Hardcoded IAP resource name (generated by Kubernetes backend policy)
  name = "projects/${data.google_project.default.number}/iap_web/compute/services/gkegw1-pl44-eave-admin-80-x6dbra8rr4l6"
}
