resource "google_iap_brand" "project" {
  application_title = "Eave"
  support_email     = "support@eave.fyi"
}

resource "google_iap_client" "default" {
  brand        = google_iap_brand.project.id
  display_name = "Default IAP Client"
}

resource "google_iap_settings" "admin_gw" {
  # FIXME: Hardcoded IAP resource name (generated by Kubernetes backend policy)
  name = "projects/${data.google_project.default.number}/iap_web/compute/services/gkegw1-pl44-eave-admin-80-x6dbra8rr4l6"

  access_settings {
    cors_settings {
      allow_http_options = true
    }
    allowed_domains_settings {
      enable  = true
      domains = ["*.vivialapp.com"]
    }
    oauth_settings {
      login_hint = "eave.fyi"
    }
    reauth_settings {
      max_age = "2592000s"
      method = "ENROLLED_SECOND_FACTORS"
      policy_type = "DEFAULT"
    }
  }
  application_settings {
    cookie_domain = "vivialapp.com"
  }
}

resource "google_iap_settings" "core_gw" {
  # FIXME: Hardcoded IAP resource name (generated by Kubernetes backend policy)
  name = "projects/${data.google_project.default.number}/iap_web/compute/services/gkegw1-pl44-eave-core-api-iap-80-y37b90pplt9n"
  access_settings {
    cors_settings {
      allow_http_options = true
    }
    allowed_domains_settings {
      enable  = true
      domains = ["*.vivialapp.com"]
    }
    oauth_settings {
      login_hint = "eave.fyi"
    }
    reauth_settings {
      max_age = "2592000s"
      method = "ENROLLED_SECOND_FACTORS"
      policy_type = "DEFAULT"
    }
  }
  application_settings {
    cookie_domain = "vivialapp.com"
  }
}
