module "iap" {
  source = "../../modules/iap"
  dns_domain = local.dns_domain
  application_title = "Eave"
  gateways = {
    # These are generated by Google Cloud from Kubernetes Gateway configs.
    "admin" = "gkegw1-pl44-eave-admin-80-x6dbra8rr4l6"
    "core_iap" = "gkegw1-pl44-eave-core-api-iap-80-y37b90pplt9n"
  }
}

moved {
  from = google_iap_brand.project
  to = module.iap.google_iap_brand.project
}

moved {
  from = google_iap_client.default
  to = module.iap.google_iap_client.default
}

moved {
  from = google_iap_settings.admin_gw
  to = module.iap.google_iap_settings.gateway["admin_gw"]
}

moved {
  from = google_iap_settings.core_gw
  to = module.iap.google_iap_settings.gateway["core_iap_gw"]
}
