runtime: nodejs18
service: atlassian

instance_class: B2
basic_scaling:
  max_instances: 1

# instance_class: F1
# automatic_scaling:
#   max_instances: 10
#   min_idle_instances: 1
# inbound_services:
# - warmup

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

env_variables:
  EAVE_API_BASE: "https://api.eave.fyi"
  EAVE_MONITORING_ENABLED: "1"
