runtime: nodejs18
service: jira

instance_class: F1
automatic_scaling:
  max_instances: 10
  min_idle_instances: 1

inbound_services:
- warmup

vpc_access_connector:
  name: projects/eave-production/locations/us-central1/connectors/appengine

handlers:
- url: /_ah/.*
  login: admin
  script: auto
  auth_fail_action: unauthorized

- url: .*
  secure: always
  redirect_http_response_code: 301
  script: auto

env_variables:
  EAVE_MONITORING_ENABLED: "1"
  EAVE_ANALYTICS_ENABLED: "1"
  LOG_LEVEL: debug