runtime: nodejs18
service: jira

instance_class: F2
automatic_scaling:
  min_idle_instances: 1

inbound_services:
- warmup

vpc_access_connector:
  name: projects/eave-production/locations/us-central1/connectors/appengine

handlers:
- url: /_ah/.*
  login: admin
  script: auto
  auth_fail_action: unauthorized

- url: .*
  secure: always
  redirect_http_response_code: 301
  script: auto

env_variables:
  EAVE_MONITORING_ENABLED: "1"
  EAVE_ANALYTICS_ENABLED: "1"
  LOG_LEVEL: "DEBUG"
  REDIS_CONNECTION: "10.81.236.179:6378:0"
  REDIS_TLS_CA: |-
    -----BEGIN CERTIFICATE-----
    MIIDnTCCAoWgAwIBAgIBADANBgkqhkiG9w0BAQsFADCBhTEtMCsGA1UELhMkN2Y0
    ZWJlN2ItMGQ4Zi00ZTNmLTlhNTUtYTRlYmUzZGY0ZWViMTEwLwYDVQQDEyhHb29n
    bGUgQ2xvdWQgTWVtb3J5c3RvcmUgUmVkaXMgU2VydmVyIENBMRQwEgYDVQQKEwtH
    b29nbGUsIEluYzELMAkGA1UEBhMCVVMwHhcNMjMwNTE4MDExMzA5WhcNMzMwNTE1
    MDExNDA5WjCBhTEtMCsGA1UELhMkN2Y0ZWJlN2ItMGQ4Zi00ZTNmLTlhNTUtYTRl
    YmUzZGY0ZWViMTEwLwYDVQQDEyhHb29nbGUgQ2xvdWQgTWVtb3J5c3RvcmUgUmVk
    aXMgU2VydmVyIENBMRQwEgYDVQQKEwtHb29nbGUsIEluYzELMAkGA1UEBhMCVVMw
    ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC5oa0KMTeb3X6MyWQxve1+
    /tkSY1nNUw7o3dqxQia8sNbn9en5BfhtQiLH6/ORS9Ghf8Lrw3tsIi70EVV8bjix
    33e3x7b8AFVbIAKQ0vzt5b8cc0ojfo1fn+2clBwIh9mdsoi+MQhkka0qLKCpR5b3
    jxRep8qswcd379KX1hrdoZKfBMR1O9L1GFNFqRqyGj8I4A/PgWg7fk1DVAt4kSAQ
    bmiquQaFCAGF5S3PzyUuiKLu7mTgSCca5RAiKaxOOZOeaw/b93YL7Pehd8Y7OSgq
    rn1R0dfCfYQp4Ciktg+0JnUJLB6v3ZN6VAhEeP2+jBaZDzn8pSmNQN3KGRKZExEH
    AgMBAAGjFjAUMBIGA1UdEwEB/wQIMAYBAf8CAQAwDQYJKoZIhvcNAQELBQADggEB
    ALeAMaQepo9QF9CZes0pOLsO2zA0PrHGZSrAwFLyCUTu2kGPmQ9UyawEHNh+pxlC
    1r4+Ug3RJl9Lzk1CvLwJTK+8PJv2iy5q7Mz9Zc8cbOvkvJVpEJUL2txMzlyBGU6r
    UlSunfOf1GyDGzNhn0jv6R4CcmkYhEsb2P7jydCvjxpe9+bhuYYXPi06JXqUQ2cG
    lCTlpPx5zbWBHd3Kb4b5MxWc4Ma0cJ3ll4llpt8S6PPgiZEfI0c070uPD1yY5iME
    uq1jBP9fCqT4qpMAaS2/XUhKF/bhZZW7dgg1jw79I/cuSY7NXof64t/uqUiasLJy
    hkL6rZr7sCEkyIC54U0DIPQ=
    -----END CERTIFICATE-----