[tool.pytest.ini_options]
addopts = "--capture=no"
pythonpath = [
  "../../../apps/core",
  "../../../apps/dashboard",
  "../../../libs/eave-stdlib-py",
  # "../../../packages/python/eave-collector-aiohttp-py",
  "../../../packages/python/eave-collector-core-py",
  # "../../../packages/python/eave-collector-flask-py",
  # "../../../packages/python/eave-collector-func-py",
  # "../../../packages/python/eave-collector-network-py",
  "../../../packages/python/eave-collector-asyncpg-py",
  "../../../packages/python/eave-collector-sqlalchemy-py",
  "../../../packages/python/eave-collector-starlette-py",
  "../../../packages/python/eave-collector-django-orm-py",
]
norecursedirs = [
  "vendor",
  "node_modules",
  "__pycache__",
  "build",
  ".*",
]
