[tool.pytest.ini_options]
addopts = "--capture=no"
pythonpath = [
  "../../../apps/core",
  "../../../apps/dashboard",
  "../../../apps/admin",
  "../../../libs/eave-stdlib-py",
]
norecursedirs = ["vendor", "node_modules", "__pycache__", "build", ".*"]
