[tool.pytest.ini_options]
addopts = "--capture=no"
pythonpath = [
  "../../../apps/core",
  "../../../apps/dashboard",
  "../../../libs/eave-stdlib-py",
]
norecursedirs = [
  "vendor",
  "node_modules",
  "__pycache__",
  "build",
  ".*",
]
