line-length = 150 # line length lint violations are suppressed by this configuration, but setting this line length informs the formatter.
extend-exclude = [
  "generated",
  "__pycache__",
  "node_modules",
  "vendor",
  "build",
  ".*",
]

[lint]
ignore-init-module-imports = true

[lint.extend-per-file-ignores]
"__init__.py" = ["PLC0414"]
"tests/*" = ["S"] # Disable security checks in test files

[lint.flake8-annotations]
allow-star-arg-any = true
