line-length = 120 # line length lint violations are suppressed by this configuration, but setting this line length informs the formatter.
extend-exclude = [
  "generated",
  "__pycache__",
  "node_modules",
  "vendor",
  "build",
  ".*",
]

[lint]
ignore-init-module-imports = true

# https://docs.astral.sh/ruff/rules/
select = [
  "F", # Pyflakes
  "E", # pycodestyle
  "W", # pycodestyle
  # "I", # isort
  # "N", # pep8-naming
  # "UP", # pyupgrade
  # "ANN", # flake8-annotations
  "ASYNC", # flake8-async
  "S", # flake8-bandit
  # "BLE", # flake8-blind-except
  # "FBT", # flake8-boolean-trap
  # "B", # flake8-bugbear
  # "B006", # https://docs.astral.sh/ruff/rules/mutable-argument-default/
  # "A", # flake8-builtins
  # "COM", # flake8-commas
  # "C4", # flake8-comprehensions
  # "DTZ", # flake8-datetimez
  # "T10", # flake8-debugger
  # "EM", # flake8-errmsg
  # "EXE", # flake8-executable
  # "ISC", # flake8-implicit-str-concat
  # "ICN", # flake8-import-conventions
  # "G", # flake8-logging-format
  # "PIE", # flake8-pie
  # "T20", # flake8-print
  # "PYI", # flake8-pyi
  # "PT", # flake8-pytest-style
  # "Q", # flake8-quotes
  # "RSE", # flake8-raise
  # "RET502", # https://docs.astral.sh/ruff/rules/implicit-return-value/
  # "RET503", # https://docs.astral.sh/ruff/rules/implicit-return/
  # "SLF", # flake8-self
  # "SLOT", # flake8-slots
  # "SIM", # flake8-simplify
  # "TID", # flake8-tidy-imports
  # "TCH", # flake8-type-checking
  # "INT", # flake8-gettext
  # "ARG", # flake8-unused-arguments
  # "PTH", # flake8-use-pathlib
  # "PD", # pandas-vet
  # "PL", # Pylint
  # "NPY", # NumPy
  # "PERF", # Perflint https://pypi.org/project/perflint/
  # "FURB", # refurb https://pypi.org/project/refurb/
  # "LOG", # flake8-logging
  # "RUF", # Ruff-specific rules
]

ignore = [
  "E501", # https://docs.astral.sh/ruff/rules/line-too-long/ - not useful
  "S101", # https://docs.astral.sh/ruff/rules/assert/ - too common in current codebase
  "ANN101", # https://docs.astral.sh/ruff/rules/missing-type-self/ - deprecated rule
  "ANN102", # https://docs.astral.sh/ruff/rules/missing-type-cls/ - deprecated rule
  "PLR09", # "too many ..." checks
  "PLW0603", # https://docs.astral.sh/ruff/rules/global-statement/ - legitimate use
  "A003", # https://docs.astral.sh/ruff/rules/builtin-attribute-shadowing/ - too common in current codebase
  "BLE001", # https://docs.astral.sh/ruff/rules/blind-except/ - too common in current codebase
]

[lint.extend-per-file-ignores]
"__init__.py" = ["PLC0414"]
"tests/*" = ["S"] # Disable security checks in test files

[lint.flake8-annotations]
allow-star-arg-any = true
