---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: metabase-cert
  namespace: "${NAMESPACE}"
spec:
  domains:
    - "metabase.${EAVE_ROOT_DOMAIN}"

---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: metabase-fc
  namespace: "${NAMESPACE}"
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metabase-ingress
  namespace: "${NAMESPACE}"
  annotations:
    networking.gke.io/v1beta1.FrontendConfig: metabase-fc
    networking.gke.io/managed-certificates: metabase-cert
    kubernetes.io/ingress.global-static-ip-name: metabase-dot-eave-dot-dev-addr
    kubernetes.io/ingress.class: gce
  labels:
    app: metabase-app
spec:
  # ingressClassName: gce # This does not work. Without the "ingress.class" annotation, the LB isn't created.
  defaultBackend:
    service:
      name: metabase
      port:
        name: http

---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: metabase-bc
spec:
  healthCheck:
    type: HTTP
    requestPath: /api/health
    port: 3000
    checkIntervalSec: 30
    unhealthyThreshold: 4
  customResponseHeaders:
    headers:
      - "server: unspecified"

---
apiVersion: v1
kind: Service
metadata:
  name: metabase
  namespace: "${NAMESPACE}"
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "metabase-bc"}'
spec:
  type: NodePort
  selector:
    app: metabase-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: app

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ksa-app-metabase
  namespace: "${NAMESPACE}"
  annotations:
    iam.gke.io/gcp-service-account: "gsa-app-metabase@${GOOGLE_CLOUD_PROJECT}.iam.gserviceaccount.com"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase-deployment
  namespace: "${NAMESPACE}"
  labels:
    app: metabase-app
spec:
  selector:
    matchLabels:
      app: metabase-app
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  template:
    metadata:
      labels:
        app: metabase-app
    spec:
      serviceAccountName: ksa-app-metabase
      dnsPolicy: ClusterFirst
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      # volumes:
      #   - name: cloudsql-socket
      #     emptyDir: {}
      containers:
        - name: metabase-enterprise
          image: "metabase/metabase-enterprise:${APP_VERSION}"
          # volumeMounts:
          #   - name: cloudsql-socket
          #     mountPath: /cloudsql
          env:
            - name: MB_DB_TYPE
              value: postgres
            - name: MB_DB_HOST
              value: "127.0.0.1"
              # value: "/cloudsql/eave-staging:us-central1:metabase"
            - name: MB_DB_PORT
              value: "5432"
          envFrom:
            - secretRef:
                name: metabase-secret
            - secretRef:
                name: metabase-jwt-shared-secret
            - configMapRef:
                name: metabase-configmap

          ports:
            - name: app
              containerPort: 3000

          resources:
            # requests and limits must always be the same on Autopilot clusters without bursting.
            # if requests is omitted, the limits values are used.
            limits:
              cpu: 500m
              memory: 2Gi

          securityContext:
            capabilities:
              drop:
              - NET_RAW

          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File

        - name: cloud-sql-proxy
          # This uses the latest version of the Cloud SQL Proxy
          # It is recommended to use a specific version for production environments.
          # See: https://github.com/GoogleCloudPlatform/cloudsql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:latest
          args:
            # If connecting from a VPC-native GKE cluster, you can use the
            # following flag to have the proxy connect over private IP
            - "--private-ip"

            # If you are not connecting with Automatic IAM, you can delete
            # the following flag.
            - "--auto-iam-authn"

            # tcp should be set to the port the proxy should listen on
            # and should match the DB_PORT value set above.
            # Defaults: MySQL: 3306, Postgres: 5432, SQLServer: 1433
            - "--port=5432"
            - "--structured-logs"
            # - "--unix-socket /cloudsql"
            - "${PG_CONNECTION_STRING}"
          # volumeMounts:
          #   - name: cloudsql-socket
          #     mountPath: /cloudsql
          securityContext:
            # The default Cloud SQL proxy image runs as the
            # "nonroot" user and group (uid: 65532) by default.
            runAsNonRoot: true

          resources:
            limits:
              cpu: 500m
              memory: 2Gi
