# Configure kubernetes provider with Oauth2 access token.
# https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/client_config
# This fetches a new token, which will expire in 1 hour.
data "google_client_config" "default" {}

data "google_project" "default" {}

data "google_compute_backend_service" "gateways" {
  for_each = {
    # These names are generated by Google Cloud from Kubernetes Gateway configs.
  }
  name = each.value
}
