# Configure kubernetes provider with Oauth2 access token.
# https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/client_config
# This fetches a new token, which will expire in 1 hour.
data "google_client_config" "default" {}

data "google_project" "default" {}

data "google_compute_backend_service" "k8s_backend_services" {
  for_each = {
    # These are generated by Google Cloud when creating a Kubernetes Gateway object.
    # I have manually copied them here because the backend services aren't managed by TF.
    dashboard = "gkegw1-vi9w-eave-dashboard-80-rmb912nmrgvv"
    api       = "gkegw1-vi9w-eave-core-api-80-em667yt9ds94"
    # admin = ""
  }

  name = each.value
}
