import {
  id = "projects/${google_cloud_project.default.number}/brands/${google_cloud_project.default.number}"
  to = module.iap.google_iap_brand.project
}

import {
  id = "projects/${google_project.default.number}/brands/${google_project.default.number}/identityAwareProxyClients/264481035543-ebotr22qbro4jbre1otq2njkacdcrb21.apps.googleusercontent.com"
  to = module.iap.google_iap_client.default
}

module "iap" {
  source = "../../modules/iap"
  dns_domain = local.dns_domain
  application_title = "Eave (Staging)"
  gateways = {
    # These are generated by Google Cloud from Kubernetes Gateway configs.
  }
}
