---
apiVersion: v1
kind: Secret
metadata:
  name: core-api-secret
  namespace: "${NAMESPACE}"
type: Opaque
stringData:
  METABASE_UI_BIGQUERY_ACCESSOR_GSA_KEY_JSON_B64: "${METABASE_UI_BIGQUERY_ACCESSOR_GSA_KEY_JSON_B64}"
