version: 1
config:
  users:
    # WARNING! Each user in Metabase (even in dev environments) are billed by Metabase at $10/user.
    - email: developer@eave.run
      password: unsafe0
      is_superuser: true

  # settings:
  #   - ...
  databases:
    - name: eavefyi-dev BigQuery
      engine: bigquery-cloud-sdk
      details:
        project-id: eavefyi-dev
        service-account-json: {{ env BQ_SERVICE_ACCOUNT_JSON }}
        dataset-filters-type: all
        advanced-options: true
        use-jvm-timezone: false
        include-user-id-and-hash: true
        ssl: true
        project-id-from-credentials: eavefyi-dev
