from decimal import Decimal
from eave.core.internal.atoms.models.openai_pricing import CHAT_MODELS, DALLE_2_MODELS, DALLE_3_MODELS, EMBEDDING_MODELS, FINE_TUNING_MODELS, MODERATION_MODELS, TRANSCRIPTION_MODELS, TTS_MODELS
from ..base import BaseTestCase

class TestOpenAIPricing(BaseTestCase):
    async def asyncSetUp(self) -> None:
        await super().asyncSetUp()

    async def test_model_pricing(self) -> None:
        assert CHAT_MODELS["gpt-4o"].calculate_input_cost_usd_cents(prompt_tokens=int(1e3)) == Decimal("5.00e-1")
        assert CHAT_MODELS["gpt-4o"].calculate_output_cost_usd_cents(completion_tokens=int(1e3)) == Decimal("15.00e-1")
        assert CHAT_MODELS["gpt-4o-2024-05-13"].calculate_input_cost_usd_cents(prompt_tokens=int(1e3)) == Decimal("5.00e-1")
        assert CHAT_MODELS["gpt-4o-2024-05-13"].calculate_output_cost_usd_cents(completion_tokens=int(1e3)) == Decimal("15.00e-1")
        assert CHAT_MODELS["gpt-4-turbo"].calculate_input_cost_usd_cents(prompt_tokens=int(1e3)) == Decimal("10.00e-1")
        assert CHAT_MODELS["gpt-4-turbo"].calculate_output_cost_usd_cents(completion_tokens=int(1e3)) == Decimal("30.00e-1")
        assert CHAT_MODELS["gpt-4-turbo-2024-04-09"].calculate_input_cost_usd_cents(prompt_tokens=int(1e3)) == Decimal("10.00e-1")
        assert CHAT_MODELS["gpt-4-turbo-2024-04-09"].calculate_output_cost_usd_cents(completion_tokens=int(1e3)) == Decimal("30.00e-1")
        assert CHAT_MODELS["gpt-4-turbo-preview"].calculate_input_cost_usd_cents(prompt_tokens=int(1e3)) == Decimal("10.00e-1")
        assert CHAT_MODELS["gpt-4-turbo-preview"].calculate_output_cost_usd_cents(completion_tokens=int(1e3)) == Decimal("30.00e-1")
        assert CHAT_MODELS["gpt-4"].calculate_input_cost_usd_cents(prompt_tokens=int(1e3)) == Decimal("30.00e-1")
        assert CHAT_MODELS["gpt-4"].calculate_output_cost_usd_cents(completion_tokens=int(1e3)) == Decimal("60.00e-1")
        assert CHAT_MODELS["gpt-4-0613"].calculate_input_cost_usd_cents(prompt_tokens=int(1e3)) == Decimal("30.00e-1")
        assert CHAT_MODELS["gpt-4-0613"].calculate_output_cost_usd_cents(completion_tokens=int(1e3)) == Decimal("60.00e-1")
        assert CHAT_MODELS["gpt-4-0125-preview"].calculate_input_cost_usd_cents(prompt_tokens=int(1e3)) == Decimal("10.00e-1")
        assert CHAT_MODELS["gpt-4-0125-preview"].calculate_output_cost_usd_cents(completion_tokens=int(1e3)) == Decimal("30.00e-1")
        assert CHAT_MODELS["gpt-4-1106-preview"].calculate_input_cost_usd_cents(prompt_tokens=int(1e3)) == Decimal("10.00e-1")
        assert CHAT_MODELS["gpt-4-1106-preview"].calculate_output_cost_usd_cents(completion_tokens=int(1e3)) == Decimal("30.00e-1")
        assert CHAT_MODELS["gpt-4-vision-preview"].calculate_input_cost_usd_cents(prompt_tokens=int(1e3)) == Decimal("10.00e-1")
        assert CHAT_MODELS["gpt-4-vision-preview"].calculate_output_cost_usd_cents(completion_tokens=int(1e3)) == Decimal("30.00e-1")
        assert CHAT_MODELS["gpt-4-32k"].calculate_input_cost_usd_cents(prompt_tokens=int(1e3)) == Decimal("60.00e-1")
        assert CHAT_MODELS["gpt-4-32k"].calculate_output_cost_usd_cents(completion_tokens=int(1e3)) == Decimal("120.00e-1")
        assert CHAT_MODELS["gpt-3.5-turbo"].calculate_input_cost_usd_cents(prompt_tokens=int(1e3)) == Decimal("0.50e-1")
        assert CHAT_MODELS["gpt-3.5-turbo"].calculate_output_cost_usd_cents(completion_tokens=int(1e3)) == Decimal("1.50e-1")
        assert CHAT_MODELS["gpt-3.5-turbo-0125"].calculate_input_cost_usd_cents(prompt_tokens=int(1e3)) == Decimal("0.50e-1")
        assert CHAT_MODELS["gpt-3.5-turbo-0125"].calculate_output_cost_usd_cents(completion_tokens=int(1e3)) == Decimal("1.50e-1")
        assert CHAT_MODELS["gpt-3.5-turbo-1106"].calculate_input_cost_usd_cents(prompt_tokens=int(1e3)) == Decimal("1.00e-1")
        assert CHAT_MODELS["gpt-3.5-turbo-1106"].calculate_output_cost_usd_cents(completion_tokens=int(1e3)) == Decimal("2.00e-1")
        assert CHAT_MODELS["gpt-3.5-turbo-0613"].calculate_input_cost_usd_cents(prompt_tokens=int(1e3)) == Decimal("1.50e-1")
        assert CHAT_MODELS["gpt-3.5-turbo-0613"].calculate_output_cost_usd_cents(completion_tokens=int(1e3)) == Decimal("2.00e-1")
        assert CHAT_MODELS["gpt-3.5-turbo-0301"].calculate_input_cost_usd_cents(prompt_tokens=int(1e3)) == Decimal("1.50e-1")
        assert CHAT_MODELS["gpt-3.5-turbo-0301"].calculate_output_cost_usd_cents(completion_tokens=int(1e3)) == Decimal("2.00e-1")
        assert CHAT_MODELS["gpt-3.5-turbo-16k"].calculate_input_cost_usd_cents(prompt_tokens=int(1e3)) == Decimal("3.00e-1")
        assert CHAT_MODELS["gpt-3.5-turbo-16k"].calculate_output_cost_usd_cents(completion_tokens=int(1e3)) == Decimal("4.00e-1")
        assert CHAT_MODELS["gpt-3.5-turbo-16k-0613"].calculate_input_cost_usd_cents(prompt_tokens=int(1e3)) == Decimal("3.00e-1")
        assert CHAT_MODELS["gpt-3.5-turbo-16k-0613"].calculate_output_cost_usd_cents(completion_tokens=int(1e3)) == Decimal("4.00e-1")
        assert CHAT_MODELS["gpt-3.5-turbo-instruct"].calculate_input_cost_usd_cents(prompt_tokens=int(1e3)) == Decimal("1.50e-1")
        assert CHAT_MODELS["gpt-3.5-turbo-instruct"].calculate_output_cost_usd_cents(completion_tokens=int(1e3)) == Decimal("2.00e-1")
        assert CHAT_MODELS["gpt-3.5-turbo-instruct-0914"].calculate_input_cost_usd_cents(prompt_tokens=int(1e3)) == Decimal("1.50e-1")
        assert CHAT_MODELS["gpt-3.5-turbo-instruct-0914"].calculate_output_cost_usd_cents(completion_tokens=int(1e3)) == Decimal("2.00e-1")
        assert CHAT_MODELS["davinci-002"].calculate_input_cost_usd_cents(prompt_tokens=int(1e3)) == Decimal("2.00e-1")
        assert CHAT_MODELS["davinci-002"].calculate_output_cost_usd_cents(completion_tokens=int(1e3)) == Decimal("2.00e-1")
        assert CHAT_MODELS["babbage-002"].calculate_input_cost_usd_cents(prompt_tokens=int(1e3)) == Decimal("0.40e-1")
        assert CHAT_MODELS["babbage-002"].calculate_output_cost_usd_cents(completion_tokens=int(1e3)) == Decimal("0.40e-1")

        assert FINE_TUNING_MODELS["gpt-3.5-turbo"].calculate_input_cost_usd_cents(prompt_tokens=int(1e3)) == Decimal("3.00e-1")
        assert FINE_TUNING_MODELS["gpt-3.5-turbo"].calculate_output_cost_usd_cents(completion_tokens=int(1e3)) == Decimal("6.00e-1")
        assert FINE_TUNING_MODELS["davinci-002"].calculate_input_cost_usd_cents(prompt_tokens=int(1e3)) == Decimal("12.00e-1")
        assert FINE_TUNING_MODELS["davinci-002"].calculate_output_cost_usd_cents(completion_tokens=int(1e3)) == Decimal("12.00e-1")
        assert FINE_TUNING_MODELS["babbage-002"].calculate_input_cost_usd_cents(prompt_tokens=int(1e3)) == Decimal("1.60e-1")
        assert FINE_TUNING_MODELS["babbage-002"].calculate_output_cost_usd_cents(completion_tokens=int(1e3)) == Decimal("1.60e-1")

        assert DALLE_2_MODELS["256x256"].calculate_total_cost_usd_cents() == Decimal("0.016e2")
        assert DALLE_2_MODELS["512x512"].calculate_total_cost_usd_cents() == Decimal("0.018e2")
        assert DALLE_2_MODELS["1024x1024"].calculate_total_cost_usd_cents() == Decimal("0.020e2")

        assert DALLE_3_MODELS["standard"]["1024x1024"].calculate_total_cost_usd_cents() == Decimal("0.04e2")
        assert DALLE_3_MODELS["standard"]["1792x1024"].calculate_total_cost_usd_cents() == Decimal("0.08e2")
        assert DALLE_3_MODELS["standard"]["1024x1792"].calculate_total_cost_usd_cents() == Decimal("0.08e2")
        assert DALLE_3_MODELS["hd"]["1024x1024"].calculate_total_cost_usd_cents() == Decimal("0.08e2")
        assert DALLE_3_MODELS["hd"]["1792x1024"].calculate_total_cost_usd_cents() == Decimal("0.12e2")
        assert DALLE_3_MODELS["hd"]["1024x1792"].calculate_total_cost_usd_cents() == Decimal("0.12e2")

        assert EMBEDDING_MODELS["text-embedding-3-small"].calculate_total_cost_usd_cents(total_tokens=int(1e3)) == Decimal("0.02e-1")
        assert EMBEDDING_MODELS["text-embedding-3-large"].calculate_total_cost_usd_cents(total_tokens=int(1e3)) == Decimal("0.13e-1")
        assert EMBEDDING_MODELS["text-embedding-ada-002"].calculate_total_cost_usd_cents(total_tokens=int(1e3)) == Decimal("0.10e-1")

        assert TTS_MODELS["tts-1"].calculate_total_cost_usd_cents(num_chars=int(1e3)) == Decimal("15.00e-1")
        assert TTS_MODELS["tts-1-1106"].calculate_total_cost_usd_cents(num_chars=int(1e3)) == Decimal("15.00e-1")
        assert TTS_MODELS["tts-1-hd"].calculate_total_cost_usd_cents(num_chars=int(1e3)) == Decimal("30.00e-1")
        assert TTS_MODELS["tts-1-hd-1106"].calculate_total_cost_usd_cents(num_chars=int(1e3)) == Decimal("30.00e-1")

        assert TRANSCRIPTION_MODELS["whisper-1"].calculate_total_cost_usd_cents(input_duration_seconds=6) == Decimal("0.006e1")

        assert MODERATION_MODELS["text-moderation-latest"].calculate_total_cost_usd_cents() == Decimal("0")
        assert MODERATION_MODELS["text-moderation-stable"].calculate_total_cost_usd_cents() == Decimal("0")
        assert MODERATION_MODELS["text-moderation-007"].calculate_total_cost_usd_cents() == Decimal("0")
