"""empty message

Revision ID: 366a56f083c3
Revises: d830556dbb6e
Create Date: 2023-01-06 21:09:25.230097

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '366a56f083c3'
down_revision = 'd830556dbb6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('github_source', table_name='github_subscriptions')
    op.drop_index('ix_github_subscriptions_document_id', table_name='github_subscriptions')
    op.drop_table('github_subscriptions')
    op.add_column('documents', sa.Column('external_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_documents_external_id'), 'documents', ['external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_external_id'), table_name='documents')
    op.drop_column('documents', 'external_id')
    op.create_table('github_subscriptions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_type', postgresql.ENUM('file', 'pull_request', 'issue', 'discussion', name='githubsourcetype'), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='github_subscriptions_pkey')
    )
    op.create_index('ix_github_subscriptions_document_id', 'github_subscriptions', ['document_id'], unique=False)
    op.create_index('github_source', 'github_subscriptions', ['source_type', 'source_id'], unique=False)
    # ### end Alembic commands ###
