"""empty message

Revision ID: d830556dbb6e
Revises: ffc0187b111b
Create Date: 2023-01-05 20:42:16.756321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd830556dbb6e'
down_revision = 'ffc0187b111b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('github_subscriptions', sa.Column('document_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_github_subscriptions_document_id'), 'github_subscriptions', ['document_id'], unique=False)
    op.add_column('slack_subscriptions', sa.Column('document_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_slack_subscriptions_document_id'), 'slack_subscriptions', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slack_subscriptions_document_id'), table_name='slack_subscriptions')
    op.drop_column('slack_subscriptions', 'document_id')
    op.drop_index(op.f('ix_github_subscriptions_document_id'), table_name='github_subscriptions')
    op.drop_column('github_subscriptions', 'document_id')
    # ### end Alembic commands ###
