"""empty message

Revision ID: ffc0187b111b
Revises: 07ca52e0dd7c
Create Date: 2023-01-02 13:37:31.640794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffc0187b111b'
down_revision = '07ca52e0dd7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('external_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_documents_external_url'), 'documents', ['external_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_url'), table_name='documents')
    op.drop_column('documents', 'url')
    # ### end Alembic commands ###
