"""empty message

Revision ID: 95187671f99a
Revises: 366a56f083c3
Create Date: 2023-01-10 22:04:19.374099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95187671f99a'
down_revision = '366a56f083c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_access_requests_visitor_id', table_name='access_requests')
    op.create_index(op.f('ix_access_requests_visitor_id'), 'access_requests', ['visitor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_access_requests_visitor_id'), table_name='access_requests')
    op.create_index('ix_access_requests_visitor_id', 'access_requests', ['visitor_id'], unique=False)
    # ### end Alembic commands ###
