"""empty message

Revision ID: 07ca52e0dd7c
Revises: d7ca973c1f1f
Create Date: 2023-01-01 13:44:59.346184

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '07ca52e0dd7c'
down_revision = 'd7ca973c1f1f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.Enum('file', 'pull_request', 'issue', 'discussion', name='githubsourcetype'), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('github_source', 'github_subscriptions', ['source_type', 'source_id'], unique=True)
    op.create_table('slack_subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.Enum('message', name='slacksourcetype'), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('slack_source', 'slack_subscriptions', ['source_type', 'source_id'], unique=True)
    op.drop_table('watches')
    op.drop_constraint('access_requests_email_key', 'access_requests', type_='unique')
    op.create_index(op.f('ix_access_requests_email'), 'access_requests', ['email'], unique=True)
    op.create_index(op.f('ix_access_requests_visitor_id'), 'access_requests', ['visitor_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_access_requests_visitor_id'), table_name='access_requests')
    op.drop_index(op.f('ix_access_requests_email'), table_name='access_requests')
    op.create_unique_constraint('access_requests_email_key', 'access_requests', ['email'])
    op.create_table('watches',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source', postgresql.ENUM('slack', 'github', 'jira', name='source'), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='watches_pkey')
    )
    op.drop_index('slack_source', table_name='slack_subscriptions')
    op.drop_table('slack_subscriptions')
    op.drop_index('github_source', table_name='github_subscriptions')
    op.drop_table('github_subscriptions')
    # ### end Alembic commands ###
