"""empty message

Revision ID: 61e675d9dc13
Revises: 95187671f99a
Create Date: 2023-01-21 16:23:20.370145

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from dotenv import load_dotenv
load_dotenv()

# revision identifiers, used by Alembic.
revision = '61e675d9dc13'
down_revision = '95187671f99a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompts',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('prompt', sa.UnicodeText(), nullable=False),
        sa.Column('response', sa.UnicodeText(), nullable=False),
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.Column('updated', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('document_platform', sa.Enum('eave', 'confluence', name='documentplatform'), nullable=False),
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.Column('updated', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('confluence_destinations',
        sa.Column('team_id', sa.Uuid(), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('url', sa.String(), nullable=False),
        sa.Column('api_username', sa.String(), nullable=False),
        sa.Column('api_key', sa.String(), nullable=False),
        sa.Column('space', sa.String(), nullable=False),
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.Column('updated', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
        sa.PrimaryKeyConstraint('team_id', 'id')
    )
    op.create_table('document_references',
        sa.Column('team_id', sa.Uuid(), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('document_id', sa.String(), nullable=False),
        sa.Column('document_url', sa.String(), nullable=False),
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.Column('updated', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
        sa.PrimaryKeyConstraint('team_id', 'id')
    )
    op.create_index('document_key', 'document_references', ['team_id', 'document_id'], unique=True)
    op.create_table('subscriptions',
        sa.Column('team_id', sa.Uuid(), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('source_platform', sa.Enum('slack', name='subscriptionsourceplatform'), nullable=False),
        sa.Column('source_event', sa.Enum('slack_message', name='subscriptionsourceevent'), nullable=False),
        sa.Column('source_id', sa.String(), nullable=False),
        sa.Column('document_reference_id', sa.Uuid(), nullable=True),
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.Column('updated', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['team_id', 'document_reference_id'], ['document_references.team_id', 'document_references.id'], ),
        sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
        sa.PrimaryKeyConstraint('team_id', 'id')
    )
    op.create_index('source_key', 'subscriptions', ['team_id', 'source_platform', 'source_event', 'source_id'], unique=True)
    op.add_column('access_requests', sa.Column('opaque_input', sa.String(), nullable=True))


    # op.drop_index('ix_documents_external_id', table_name='documents')
    # op.drop_index('ix_documents_external_url', table_name='documents')
    # op.drop_table('documents')
    # op.drop_index('ix_slack_subscriptions_document_id', table_name='slack_subscriptions')
    # op.drop_index('slack_source', table_name='slack_subscriptions')
    # op.drop_table('slack_subscriptions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('access_requests', 'opaque_input')
    op.create_table('slack_subscriptions',
        sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('source_type', postgresql.ENUM('message', name='slacksourcetype'), autoincrement=False, nullable=False),
        sa.Column('source_id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('id', name='slack_subscriptions_pkey')
    )
    op.create_index('slack_source', 'slack_subscriptions', ['source_type', 'source_id'], unique=False)
    op.create_index('ix_slack_subscriptions_document_id', 'slack_subscriptions', ['document_id'], unique=False)
    op.create_table('documents',
        sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column('external_url', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('external_id', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('id', name='documents_pkey')
    )
    op.create_index('ix_documents_external_url', 'documents', ['external_url'], unique=False)
    op.create_index('ix_documents_external_id', 'documents', ['external_id'], unique=False)
    op.drop_index('source_key', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('document_key', table_name='document_references')
    op.drop_table('document_references')
    op.drop_table('confluence_destinations')
    op.drop_index('not_revoked', table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_revoked'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('teams')
    op.drop_table('prompts')
    # ### end Alembic commands ###
