"""empty message

Revision ID: a48fb0a28deb
Revises: d2e640c9a299
Create Date: 2022-12-30 13:28:04.598000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a48fb0a28deb'
down_revision = 'd2e640c9a299'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.Enum('slack', 'github', 'jira', name='source'), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watches')
    # ### end Alembic commands ###
