runtime: python311
service: www

instance_class: F1
automatic_scaling:
  max_instances: 10
  min_idle_instances: 1

inbound_services:
- warmup

vpc_access_connector:
  name: projects/eave-production/locations/us-central1/connectors/appengine

entrypoint: |-
  gunicorn \
    --bind :$PORT \
    --pythonpath vendor \
    --workers 3 \
    --preload \
    eave.marketing.app:app

env_variables:
  EAVE_ANALYTICS_ENABLED: "1"
  EAVE_MONITORING_ENABLED: "1"

handlers:
- url: /static
  static_dir: eave/marketing/static

- url: /_ah/.*
  login: admin
  script: auto

- url: .*
  script: auto
