export const AppRoute = {
  root: "/",
  login: "/login",
  logout: "/logout",
  forgotPassword: "/login/password",
  signup: "/signup",
  account: "/account",
  plans: "/plans",
  help: "/help",
  terms: "/terms",
  privacy: "/privacy",
  bookingConfirmation: "/booking-confirmation",
  payment: "/payment-example",
  accountPreferences: "/account/preferences",
  passwordReset: "/account/password",
};
