[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "eave-collector-sqlalchemy"
version = "0.1.0"
requires-python = ">=3.12.0"
dependencies = [
  "sqlalchemy",
  "sqlglot",
  "eave-collector-core"
]