"""change visitor_id column type

Revision ID: 3328220ced57
Revises: 69869c7cb049
Create Date: 2024-04-26 09:25:12.321141

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3328220ced57"
down_revision: str | None = "69869c7cb049"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "visitor_id", existing_type=sa.UUID(), type_=sa.String(), existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "visitor_id", existing_type=sa.String(), type_=sa.UUID(), existing_nullable=True)
    # ### end Alembic commands ###
