"""empty message

Revision ID: b806fa046c93
Revises: cc8f292a5bc3
Create Date: 2023-03-14 00:38:20.568624

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b806fa046c93"
down_revision = "cc8f292a5bc3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "auth_provider",
            sa.Enum("google", name="authprovider"),
            nullable=False,
        ),
        sa.Column("auth_id", sa.String(), nullable=False),
        sa.Column("oauth_token", sa.String(), nullable=False),
        sa.Column(
            "created",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("team_id", "id"),
    )
    op.create_index(
        "auth_provider_auth_id",
        "accounts",
        ["auth_provider", "auth_id"],
        unique=True,
    )
    op.drop_table("prompts")
    op.alter_column(
        "confluence_destinations",
        "updated",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "document_references",
        "updated",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "subscriptions",
        "updated",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "teams",
        "document_platform",
        existing_type=postgresql.ENUM(
            "eave", "confluence", name="documentplatform"
        ),
        nullable=True,
    )
    op.alter_column(
        "teams", "updated", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    # ### end Alembic commands ###

    op.execute("alter type documentplatform add value 'google_drive'")

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "teams",
        "updated",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column(
        "teams",
        "document_platform",
        existing_type=postgresql.ENUM(
            "eave", "confluence", name="documentplatform"
        ),
        nullable=False,
    )
    op.alter_column(
        "subscriptions",
        "updated",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column(
        "document_references",
        "updated",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column(
        "confluence_destinations",
        "updated",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.create_table(
        "prompts",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("prompt", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("response", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "created",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="prompts_pkey"),
    )
    op.drop_index("auth_provider_auth_id", table_name="accounts")
    op.drop_table("accounts")
    # ### end Alembic commands ###
