steps:
- name: python:3.11.2
  dir: apps/core
  entrypoint: bin/setup
  env:
  - EAVE_HOME=$_EAVE_HOME
  - CI=1
  - VERBOSE=1

- name: python:3.11.2
  dir: apps/core
  entrypoint: bin/lint
  env:
  - EAVE_HOME=$_EAVE_HOME
  - CI=1
  - VERBOSE=1

- name: python:3.11.2
  dir: apps/core
  entrypoint: bin/test
  env:
  - EAVE_HOME=$_EAVE_HOME
  - CI=1
  - VERBOSE=1

- name: python:3.11.2
  dir: apps/core
  entrypoint: bin/deploy
  env:
  - EAVE_HOME=$_EAVE_HOME
  - CI=1
  - VERBOSE=1
  - GOOGLE_CLOUD_PROJECT=$PROJECT_ID

# - name: python:3.11.2
#   dir: apps/core
#   entrypoint: bin/run-db-migration
#   env:
#   - EAVE_HOME=$_EAVE_HOME
#   - CI=1
#   - VERBOSE=1
#   secretEnv:
#   - EAVE_DB_HOST
#   - EAVE_DB_USER
#   - EAVE_DB_PASS
#   - EAVE_DB_NAME

# availableSecrets:
#   secretManager:
#   - versionName: projects/$PROJECT_ID/secrets/EAVE_DB_HOST/versions/latest
#     env: 'EAVE_DB_HOST'
#   - versionName: projects/$PROJECT_ID/secrets/EAVE_DB_USER/versions/latest
#     env: 'EAVE_DB_USER'
#   - versionName: projects/$PROJECT_ID/secrets/EAVE_DB_PASS/versions/latest
#     env: 'EAVE_DB_PASS'
#   - versionName: projects/$PROJECT_ID/secrets/EAVE_DB_NAME/versions/latest
#     env: 'EAVE_DB_NAME'

substitutions:
  _EAVE_HOME: /workspace

timeout: '1600s'
