steps:
- name: python:3.11.2
  dir: apps/core
  entrypoint: bin/setup
  env:
  - EAVE_HOME=/workspace
  - CI=1
  - VERBOSE=1
  - GOOGLE_CLOUD_PROJECT=$PROJECT_ID
  - PYTHONDONTWRITEBYTECODE=1

- name: python:3.11.2
  dir: apps/core
  entrypoint: bin/lint
  env:
  - EAVE_HOME=/workspace
  - CI=1
  - VERBOSE=1
  - GOOGLE_CLOUD_PROJECT=$PROJECT_ID
  - PYTHONDONTWRITEBYTECODE=1

# - name: python:3.11.2
#   dir: apps/core
#   entrypoint: bin/test
#   env:
#   - EAVE_HOME=/workspace
#   - CI=1
#   - VERBOSE=1
#   - GOOGLE_CLOUD_PROJECT=$PROJECT_ID
#   secretEnv:
#   - EAVE_DB_HOST
#   - EAVE_DB_USER
#   - EAVE_DB_PASS
#   - EAVE_DB_NAME

- name: python:3.11.2
  dir: apps/core
  script: |-
    python -m pip install -t vendor -r requirements-vendor.txt
  env:
  - EAVE_HOME=/workspace

- name: bash
  dir: apps/core
  script: |-
    cp $EAVE_HOME/.gcloudignore .
    cp $EAVE_HOME/.gitignore .
  env:
  - EAVE_HOME=/workspace

- name: git
  dir: apps/core
  script: |-
    #!/usr/bin/env bash
    (
      mkdir .buildinfo
      local timestamp=$(date --utc "+%Y%m%dt%H%Mz")
      local gitrev=$(git rev-parse --short HEAD)
      echo -n "$timestamp-$gitrev" >> .buildinfo/version
    )

- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  dir: apps/core
  script: |-
    #!/usr/bin/env bash
    (
      local version=$(cat .buildinfo/version)
      gcloud app deploy \
        --version=$version \
        --appyaml=app.$GOOGLE_CLOUD_PROJECT.yaml
    )
  env:
  - EAVE_HOME=/workspace
  - GOOGLE_CLOUD_PROJECT=$PROJECT_ID


# - name: python:3.11.2
#   dir: apps/core
#   entrypoint: bin/run-db-migration
#   env:
#   - EAVE_HOME=$_EAVE_HOME
#   - CI=1
#   - VERBOSE=1
#   secretEnv:
#   - EAVE_DB_HOST
#   - EAVE_DB_USER
#   - EAVE_DB_PASS
#   - EAVE_DB_NAME

# availableSecrets:
#   secretManager:
#   - versionName: projects/$PROJECT_ID/secrets/EAVE_DB_HOST/versions/latest
#     env: 'EAVE_DB_HOST'
#   - versionName: projects/$PROJECT_ID/secrets/EAVE_DB_USER_CI/versions/latest
#     env: 'EAVE_DB_USER'
#   - versionName: projects/$PROJECT_ID/secrets/EAVE_DB_PASS_CI/versions/latest
#     env: 'EAVE_DB_PASS'
#   - versionName: projects/$PROJECT_ID/secrets/EAVE_DB_NAME_CI/versions/latest
#     env: 'EAVE_DB_NAME'

timeout: '1600s'
