#!/usr/bin/env bash

set -eu

source "${EAVE_HOME}"/develop/functions.bash

(
	python-format .
	if ! ^onlythismodule; then
		"${EAVE_HOME}"/libs/eave-stdlib-py/bin/format
		"${EAVE_HOME}"/libs/eave-monitoring/bin/format
		"${EAVE_HOME}"/libs/eave-pubsub-schemas/python/bin/format
	fi
)
