#!/usr/bin/env bash

set -eu

source "${EAVE_HOME}"/develop/functions.bash

(
	python-lint .
	if ! ^onlythismodule; then
		"${EAVE_HOME}"/libs/eave-stdlib-py/bin/lint
		"${EAVE_HOME}"/libs/eave-pubsub-schemas/python/bin/lint

		for formatter in "${EAVE_HOME}"/libs/python/*/bin/format; do
			$formatter
		done
	fi
)
