#!/usr/bin/env bash

set -eu

source "${EAVE_HOME}"/develop/functions.bash

(
	python-test .
	if test -z "${_ONLY_THIS_MODULE:-}"; then
		"${EAVE_HOME}"/libs/eave-stdlib-py/bin/test
		"${EAVE_HOME}"/libs/eave-pubsub-schemas/python/bin/test
	fi
)
