#!/usr/bin/env bash

set -eu

source "${EAVE_HOME}"/develop/functions.bash

(
	python-test .
	if ! ^onlythismodule; then
		"${EAVE_HOME}"/libs/eave-stdlib-py/bin/test
		"${EAVE_HOME}"/libs/eave-pubsub-schemas/python/bin/test
		"${EAVE_HOME}"/libs/eave-tracing-core-py/bin/test
		"${EAVE_HOME}"/libs/eave-tracing-python/bin/test
		"${EAVE_HOME}"/libs/eave-tracing-postgres/bin/test
	fi
)
