runtime: python311
service: slack

instance_class: F1
automatic_scaling:
  max_instances: 10
  min_idle_instances: 1

inbound_services:
- warmup

vpc_access_connector:
  name: projects/eave-production/locations/us-central1/connectors/appengine

entrypoint: |-
  gunicorn \
    --bind :$PORT \
    --pythonpath vendor \
    --workers 3 \
    --worker-class uvicorn.workers.UvicornWorker \
    --preload \
    eave.slack.app:api

handlers:
- url: /_ah/.*
  login: admin
  script: auto

- url: .*
  script: auto

env_variables:
  EAVE_MONITORING_ENABLED: "1"
