runtime: python311
service: slack

instance_class: F2
automatic_scaling:
  max_instances: 10
  min_idle_instances: 1

inbound_services:
- warmup

vpc_access_connector:
  name: projects/eave-production/locations/us-central1/connectors/appengine

# Don't use --preload, it breaks Google Cloud Logging and AppEngine
entrypoint: |-
  gunicorn \
    --bind :$PORT \
    --pythonpath vendor \
    --workers 3 \
    --worker-class uvicorn.workers.UvicornWorker \
    eave.slack.app:api

handlers:
- url: /_.*
  script: auto
  login: admin
  auth_fail_action: unauthorized

- url: .*
  script: auto

env_variables:
  EAVE_MONITORING_ENABLED: "1"
  EAVE_ANALYTICS_ENABLED: "1"
