# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: document_platform.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x64ocument_platform.proto*a\n\x10\x44ocumentPlatform\x12!\n\x1d\x44OCUMENT_PLATFORM_UNSPECIFIED\x10\x00\x12\x08\n\x04\x45\x41VE\x10\x01\x12\x0e\n\nCONFLUENCE\x10\x02\x12\x10\n\x0cGOOGLE_DRIVE\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'document_platform_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_DOCUMENTPLATFORM']._serialized_start=27
  _globals['_DOCUMENTPLATFORM']._serialized_end=124
# @@protoc_insertion_point(module_scope)
